Repository iterative/vscode-dvc, pull requests merged in 2022-10, with the labels that each got.

#2520 Move types from reader into new contract file
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.ts
  extension/src/data/index.ts
  extension/src/experiments/columns/collect/deps.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/data/collect.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/modify/collect.ts
  extension/src/experiments/model/modify/quickPick.ts
  extension/src/experiments/webview/contract.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/multiSource/collect.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.ts
  extension/src/repository/data/index.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/index.ts
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/fixtures/expShow/dataTypes.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/test/fixtures/expShow/noErrors.ts
  extension/src/test/fixtures/expShow/output.ts
  extension/src/test/fixtures/expShow/uncommittedDeps.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/repository/util.ts
  webview/src/experiments/util/buildDynamicColumns.tsx
Labels: 🏠 housekeeping

#2517 Update table header context menu
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/vscode/config.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/TableHeader.tsx
Labels: product

#2526 Switch e2e tests back to insiders build
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#2533 Fix comparison table row path chevron being cut
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: bug

#2531 Fix size of flexible confusion matrix
  extension/src/experiments/model/index.ts
  extension/src/plots/model/collect.ts
  extension/src/test/suite/plots/index.test.ts
Labels: bug

#2536 Bump min tested version of DVC to 2.29.0
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2525 Add test for setting table header depth
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/table/Table.test.tsx
Labels: 🏠 housekeeping

#2544 Fix UX of extension using fallback global CLI when Python extension is active
  extension/src/cli/dvc/version.test.ts
  extension/src/cli/dvc/version.ts
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/test/suite/extension.test.ts
Labels: bug

#2552 Consolidate version checking into CLI discovery file
  extension/src/cli/dvc/discovery.ts
  extension/src/cli/dvc/version.ts
  extension/src/setup.ts
Labels: 🏠 housekeeping

#2521 Bump min DVC version to 2.30.0 (Use status from exp show)
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/accumulator.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/sortBy/index.test.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/model/status/index.test.ts
  extension/src/experiments/model/status/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/plots/model/collect.ts
  extension/src/test/fixtures/expShow/dataTypes.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/test/fixtures/expShow/modified.ts
  extension/src/test/fixtures/expShow/output.ts
  extension/src/test/fixtures/expShow/rows.ts
  extension/src/test/fixtures/expShow/uncommittedDeps.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/tableDataFixture.ts
Labels: 🏠 housekeeping, do not merge

#2535 Display failed experiments
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/model/collect.ts
  extension/src/test/fixtures/expShow/output.ts
  extension/src/test/fixtures/expShow/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#2561 Remove stale developer roadmap from README
  README.md
Labels: 🏠 housekeeping

#2538 Improve max table depth feature
  README.md
  extension/package.json
  extension/package.nls.json
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/config.ts
  extension/src/vscode/inputBox.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/TableHeader.tsx
Labels: product

#2571 Account for dvc yaml potentially not having a train stage
  extension/src/experiments/checkpoints/collect.test.ts
  extension/src/experiments/checkpoints/collect.ts
  extension/src/fileSystem/index.ts
Labels: bug

#2580 Fix failing CI vscode test
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#2587 Use error foreground for status bar item color if CLI unavailable
  extension/src/status.ts
Labels: product

#2553 Change experiments table circle to radio button
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2567 Add hints into experiment table row action tooltips
  webview/src/experiments/components/table/CellRowActions.tsx
Labels: product

#2594 Revert moving experiment names to right in table's experiment column (maintain heirarchy)
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#2595 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 🏠 housekeeping

#2590 Follow directions in the VS Code API docs for relative paths
  extension/src/fileSystem/watcher.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
  extension/src/test/suite/fileSystem/watcher.test.ts
  extension/src/test/util/index.ts
Labels: bug

#2611 Use stable version of VS Code for e2e tests (again)
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#2606 Add actions to experiment cell hint tooltips
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/CellHintTooltip.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/messages.ts
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#2597 Standardize dvc root paths as they come into the system
  extension/src/fileSystem/index.ts
Labels: 🏠 housekeeping

#2604 Update experiment table icons to use --vscode-descriptionForeground and use --vscode-editorLightBulb-foreground for selected stars
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2617 Account for null being an object in workspace change data collection
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
Labels: bug

#2619 Add util for identifying ValueTree type
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/model/modify/collect.ts
  extension/src/plots/model/collect.ts
Labels: 🏠 housekeeping

#2623 Switch CI test coverage to use stable build
  extension/src/test/runTest.ts
Labels: 🏠 housekeeping

#2615 Upload vsix as part of publish action
  .github/workflows/publish.yml
Labels: 🏠 housekeeping

#2622 Plots improve section tooltips copy and style
  extension/resources/walkthrough/plots.md
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/styles.module.scss
Labels: product

#2621 Improve max table depth test
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#2625 Experiments Table Headers - Remove context menu's click trigger
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
Labels: enhancement, A: table

#2632 Do not toggle plot section when clicking a link
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/util/objects.ts
Labels: bug

#2628 Fix integration test suite after hook
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/config.ts
Labels: 🏠 housekeeping

#2629 Only patch workspace only calls to plots diff
  extension/src/plots/data/index.ts
  extension/src/plots/model/index.ts
  extension/src/test/suite/plots/data/index.test.ts
Labels: bug

#2563 Make the plot sizes use numbers underneath
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/checkpointPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/SizePicker.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/util.ts
  webview/src/plots/hooks/useNbItemsPerRow.ts
  webview/src/shared/components/virtualizedGrid/VirtualizedGrid.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/util.ts
  webview/src/util/strings.ts
Labels: 🏠 housekeeping

#2627 Split standardize path into two functions
  extension/src/cli/git/executor.test.ts
  extension/src/cli/git/index.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/context.ts
  extension/src/fileSystem/index.ts
  extension/src/fileSystem/path.ts
  extension/src/repository/sourceControlManagement/decorationProvider.test.ts
  extension/src/test/suite/fileSystem/index.test.ts
Labels: 🏠 housekeeping

#2634 Do not run build twice in CI
  extension/package.json
  extension/scripts/coverIntegrationTests.js
  languageServer/package.json
  turbo.json
  webview/package.json
Labels: 🏠 housekeeping

#2639 Add revisions to scheduled plots diff demo repo test (required for submodule to behave like a git repo)
  extension/src/test/cli/plotsDiff.test.ts
Labels: 🏠 housekeeping

#2635 Rearrange exp show fixtures
  extension/src/cli/dvc/reader.test.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/tree.test.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/modify/collect.test.ts
  extension/src/plots/model/collect.test.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/fixtures/expShow/base/noErrors.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/base/workspaceChanges.ts
  extension/src/test/fixtures/expShow/dataTypes/columns.ts
  extension/src/test/fixtures/expShow/dataTypes/output.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/columns.ts
  extension/src/test/fixtures/expShow/deeplyNested/maxHeight.ts
  extension/src/test/fixtures/expShow/deeplyNested/output.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/metrics.ts
  extension/src/test/fixtures/expShow/modified/output.ts
  extension/src/test/fixtures/expShow/uncommittedDeps/output.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/filterBy/util.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/util/buildDynamicColumns.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#2638 Add survival exp show test fixture
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/model/index.test.ts
  extension/src/test/fixtures/expShow/survival/columns.ts
  extension/src/test/fixtures/expShow/survival/output.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  webview/src/stories/Table.stories.tsx
Labels: 🏠 housekeeping

#2642 Do not toggle plot section on tooltip click
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/util/objects.ts
Labels: bug

#2654 Remove undici yarn resolution
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#2650 Update packages to fix d3-color vulnerability
  package.json
  webview/package.json
  yarn.lock
Labels: bug

#2651 Update packages to fix minimatch vulnerability
  package.json
  yarn.lock
Labels: bug

#2652 Update packages to fix terser vulnerability
  package.json
  yarn.lock
Labels: bug

#2661 Set CLI as available for project initialization purposes
  extension/src/setup.test.ts
  extension/src/setup.ts
Labels: bug

#2670 Add experiment details when selecting exps for plots
  extension/src/experiments/columns/model.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPicks.ts
  extension/src/util/date.ts
Labels: product

#2588 Changing images with code to code snippets
  extension/resources/walkthrough/images/plots-dump-image.png
  extension/resources/walkthrough/images/plots-dump-with-dvclive.png
  extension/resources/walkthrough/images/plots-dump-with-open-file.png
  extension/resources/walkthrough/images/setup-project-dump-metrics.png
  extension/resources/walkthrough/images/setup-project-dvc-yaml-example.png
  extension/resources/walkthrough/images/setup-project-dvclive-metrics.png
  extension/resources/walkthrough/plots.md
  extension/resources/walkthrough/setup-project.md
Labels: product

#2694 Fix missing exp selection quick pick details on inital extension render
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
Labels: bug

#2697 Fix scheduled CLI output test by moving TEMP_DIR outside of Git repository
  extension/src/cli/git/constants.ts
  extension/src/cli/git/executor.ts
  extension/src/test/cli/constants.ts
  extension/src/test/cli/expShow.test.ts
  extension/src/test/cli/util.ts
Labels: bug
