Repository iterative/vscode-dvc, pull requests merged in 2022-07, with the labels that each got.

#1962 Improve quick start in README
  README.md
Labels: 🏠 housekeeping

#1963 Only pull selected files if they include the invoked path
  extension/src/fileSystem/tree.ts
  extension/src/repository/model/collect.test.ts
  extension/src/repository/model/collect.ts
Labels: product

#1965 Upgrade React to v18
  .lintstagedrc.js
  package.json
  webview/.storybook/main.ts
  webview/__mocks__/@vscode/webview-ui-toolkit/react.tsx
  webview/package.json
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/react-table-config.d.ts
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.tsx
  webview/src/shared/components/copyButton/CopyButton.test.tsx
  webview/src/shared/components/dragDrop/DragDropContext.tsx
  webview/src/shared/components/emptyState/EmptyState.tsx
  webview/src/shared/components/modal/Modal.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/test/dragDrop.ts
  yarn.lock
Labels: 🏠 housekeeping

#1964 Implement checkbox selection
  webview/__mocks__/@vscode/webview-ui-toolkit/react.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/util/props.ts
Labels: product

#1970 Increase timeout of integration tests again
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/fileSystem/tree.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/util/mocha/index.ts
Labels: 🏠 housekeeping

#1969 More dependency updates
  .eslintrc.js
  .github/workflows/continuous-integration.yml
  .github/workflows/cross-platform-test.yml
  .github/workflows/dvc-cli-output-test.yml
  .github/workflows/publish.yml
  extension/package.json
  package.json
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#1971 Use create root to instantiate React apps
  extension/src/webview/index.ts
  webview/src/experiments/index.tsx
  webview/src/plots/index.tsx
  webview/src/shared/style.scss
Labels: 🏠 housekeeping

#1967 Small table cell tooltip changes
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/shared/components/tooltip/styles.module.scss
Labels: product

#1988 Fix plot colors
  webview/src/plots/components/constants.ts
Labels: bug

#1986 Fix checkbox selection issues
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/interfaces.ts
  webview/src/shared/components/messagesMenu/MessagesMenuOption.tsx
Labels: bug

#1992 Add stability days to Renovate config
  renovate.json
Labels: 🏠 housekeeping

#1993 Add e2e tests (wdio-vscode-service)
  extension/.gitignore
  extension/package.json
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/pageObjects/baseWebview.ts
  extension/src/test/e2e/pageObjects/experimentsWebview.ts
  extension/src/test/e2e/pageObjects/locators.ts
  extension/src/test/e2e/pageObjects/plotsWebview.ts
  extension/src/test/e2e/util.ts
  extension/src/test/e2e/wdio.conf.ts
  package.json
  turbo.json
  yarn.lock
Labels: 🏠 housekeeping

#1998 Add matchLanguages to Renovate config
  renovate.json
Labels: 🏠 housekeeping

#2001 Add internalChecksFilter to Renovate config
  renovate.json
Labels: 🏠 housekeeping

#2011 Fix race condition in manual plot refresh (M1 macs)
  extension/src/plots/index.ts
  extension/src/test/suite/plots/index.test.ts
Labels: 🏠 housekeeping

#2014 Remove flaky test from unit test suite
  extension/src/git.test.ts
Labels: 🏠 housekeeping

#2002 Add e2e tests into CI
  .github/workflows/continuous-integration.yml
  .github/workflows/cross-platform-test.yml
  demo/training_metrics.json
  extension/.gitignore
  extension/src/python/index.ts
  extension/src/python/path.ts
  extension/src/test/cli/util.ts
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/pageObjects/baseWebview.ts
  extension/src/test/e2e/pageObjects/experimentsWebview.ts
  extension/src/test/e2e/pageObjects/locators.ts
  extension/src/test/e2e/util.ts
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping, 🛠️ test

#2013 Add end to end test for SCM and file decorations
  extension/src/repository/decorationProvider.ts
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/util.ts
Labels: 🏠 housekeeping

#2018 Add Julie to CODEOWNERS
  .github/CODEOWNERS
Labels: 🏠 housekeeping

#2016 Add storybook-addon-themes
  webview/.storybook/main.ts
  webview/.storybook/preview.ts
  webview/package.json
  webview/src/stories/test-vscode-styles.scss
  yarn.lock
Labels: 🏠 housekeeping

#2015 Minor Storybook config touch-ups
  webview/.storybook/main.ts
  webview/.storybook/preview.ts
  webview/package.json
  webview/src/stories/test-vscode-styles.scss
  yarn.lock
Labels: 🏠 housekeeping

#2010 Conditional sticky table head shadows
  webview/package.json
  webview/setup-tests.js
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/Table.stories.tsx
  yarn.lock
Labels: product

#2021 Ignore packages in Renovate config
  renovate.json
Labels: 🏠 housekeeping

#2025 Increase timeout of scheduled CLI test
  extension/src/test/cli/index.ts
Labels: 🏠 housekeeping

#2026 Remove webview message handling from experiments
  extension/src/experiments/index.ts
  extension/src/experiments/webview/messages.ts
Labels: 🏠 housekeeping

#2027 Remove webview message handling from plots
  extension/src/plots/index.ts
  extension/src/plots/webview/messages.ts
Labels: 🏠 housekeeping

#2024 Upgrade Python dependencies
  .github/workflows/continuous-integration.yml
  demo/requirements.txt
Labels: 🏠 housekeeping

#2004 Show middle state badges for running, starred and checked sub-rows
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/components/contextMenu/ContextMenu.tsx
  webview/src/shared/components/tooltip/Tooltip.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/tableDataFixture.ts
  webview/src/util/strings.ts
Labels: product

#2054 Change type of cell value as a step towards consolidation
  webview/src/experiments/util/buildDynamicColumns.tsx
Labels: 🏠 housekeeping

#2030 Move experiments webview message sending into WebviewMessages
  extension/src/experiments/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/webview/repository.ts
Labels: 🏠 housekeeping

#2033 Move plots webview message sending into WebviewMessages
  extension/src/plots/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
Labels: 🏠 housekeeping

#2038 Extract set active editor context from experiments
  extension/src/experiments/context.ts
  extension/src/experiments/index.ts
Labels: 🏠 housekeeping

#2042 Do not update trees on star update
  extension/src/experiments/webview/messages.ts
Labels: 🏠 housekeeping

#2056 Move some App.test.tsx helpers to utils
  .eslintrc.js
  webview/src/experiments/components/App.test.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#2061 Exclude integration and e2e test folders from unit test discovery
  extension/jest.config.js
Labels: 🏠 housekeeping

#2065 Add selected for plotting indicator to experiments webview
  extension/src/experiments/webview/messages.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/util/rows.ts
  webview/src/shared/components/icons/GraphScatter.tsx
Labels: product

#2062 Add conditional shadow to sticky experiments column
  webview/src/experiments/components/table/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/isFirstInArr.ts
Labels: product

#2072 Highlight experiments with errors
  .vscode/settings.json
  extension/src/experiments/columns/extract.test.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/decorationProvider.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/noErrors.ts
  extension/src/test/fixtures/expShow/output.ts
  extension/src/test/fixtures/expShow/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/vscode/markdownString.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Errors.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/shared/components/icons/Error.tsx
  webview/src/shared/variables.scss
Labels: product

#2079 Standardize how the webviews access icons
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Errors.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/shared/components/copyButton/CopyButton.tsx
  webview/src/shared/components/icons/index.ts
Labels: 🏠 housekeeping

#2064 Comparison table drag and drop feedback
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/DropTarget.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DragDropWorkbench.tsx
  webview/src/shared/components/dragDrop/styles.module.scss
  webview/src/test/dragDrop.ts
  webview/src/test/nodes.ts
Labels: product

#2077 Change the style of the comparison drag and drop feedback
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
Labels: product

#2082 Add more resolutions for security advisories in dev dependencies
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#2083 Move divider to top of group in experiments table context menu
  webview/src/experiments/components/table/Row.tsx
  webview/src/stories/Table.stories.tsx
Labels: bug

#2085 Refactor experiments column conditional shadow logic
  webview/src/experiments/components/table/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/util/isFirstInArr.ts
Labels: 🏠 housekeeping

#2087 Fix cell tooltip position on table column resize
  webview/src/experiments/util/buildDynamicColumns.tsx
Labels: bug

#2086 Add getParentelem helper for tests
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/test/experimentsTable.tsx
  webview/src/test/queries.ts
Labels: 🏠 housekeeping

#2095 Avoid name clashing when naming redux objects
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/index.tsx
  webview/src/plots/store.ts
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#2088 Style the ghost image of the comparison table dragged item
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/styles.module.scss
  webview/src/test/dragDrop.ts
  webview/src/test/nodes.ts
  webview/src/util/helpers.ts
  webview/src/util/styles.ts
Labels: product

#2098 Do not use turbo cache on main
  .github/workflows/continuous-integration.yml
  .github/workflows/cross-platform-test.yml
Labels: 🏠 housekeeping

#2101 Fix `yarn build` by reverting "chore(deps): update dependency vsce to v2.9.3"
  extension/package.json
  yarn.lock
Labels: bug

#2104 Undo failed release attempt by reverting "Update version and CHANGELOG for release"
  CHANGELOG.md
  extension/package.json
Labels: bug

#2097 Redux for experiments table drag and drop
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/index.tsx
  webview/src/experiments/store.ts
  webview/src/shared/components/dragDrop/DragDropContext.tsx
  webview/src/shared/components/dragDrop/DragDropWorkbench.tsx
  webview/src/shared/components/dragDrop/dragDropSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#2108 Upgrade vsce
  extension/.vscodeignore
  extension/package.json
  extension/scripts/ensureYarnLock.js
  yarn.lock
Labels: 🏠 housekeeping

#2112 Table data in redux
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/headersSlice.ts
  webview/src/experiments/components/table/interfaces.ts
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/experiments/store.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#2114 Keep old reference in the state if they have not changed
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/util/array.ts
  webview/src/util/objects.ts
Labels: 🏠 housekeeping
