Repository iterative/vscode-dvc, pull requests merged in 2022-08, with the labels that each got.

#2124 Upgrade wdio-vscode-service
  extension/package.json
  yarn.lock
Labels: 🏠 housekeeping

#2126 Simplify drag and drop integrations
  webview/src/experiments/components/table/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/Draggable.tsx
  webview/src/shared/components/dragDrop/DropTarget.tsx
Labels: 🏠 housekeeping

#2128 Block users from attempting to run concurrent SCM commands
  extension/package.json
  extension/src/cli/executor.test.ts
  extension/src/cli/executor.ts
  extension/src/repository/commands/index.test.ts
  extension/src/repository/commands/index.ts
  extension/src/test/suite/repository/sourceControlManagement.test.ts
Labels: bug

#2125 Add scheduled data status cli output test
  extension/src/cli/reader.test.ts
  extension/src/cli/reader.ts
  extension/src/repository/data/index.ts
  extension/src/test/cli/dataStatus.test.ts
Labels: 🏠 housekeeping

#2132 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 🏠 housekeeping

#2131 Hide remove all buttons from trees when there is nothing to remove
  extension/package.json
  extension/src/context.ts
  extension/src/test/suite/context.test.ts
Labels: product

#2137 Plot experiments in the order they were selected
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/util/array.ts
Labels: product

#2140 Links in section description tooltips
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
Labels: product

#2143 Patch e2e tests
  extension/package.json
  extension/src/test/e2e/wdio.conf.ts
  yarn.lock
Labels: bug

#2147 Retain plot order when toggling off/on
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
Labels: product

#2145 All plots sections visible
  .eslintrc.js
  webview/package.json
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/plotDataStore.ts
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
Labels: product

#2149 Remove drop target when leaving a section
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/dragDropSlice.ts
Labels: bug

#2165 Split up `Table.tsx`
  webview/src/experiments/components/table/ExperimentGroup.tsx
  webview/src/experiments/components/table/NestedRow.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
Labels: 🏠 housekeeping

#2164 Add option to filter experiments to starred
  extension/src/experiments/columns/like.ts
  extension/src/experiments/columns/quickPick.test.ts
  extension/src/experiments/columns/quickPick.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/index.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/sortBy/quickPick.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/dataTypes.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/test/fixtures/expShow/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/filterBy/util.ts
Labels: product

#2169 Add option to sort by starred experiments
  extension/src/experiments/index.ts
  extension/src/experiments/model/sortBy/quickPick.ts
Labels: product

#2170 Add shortcut to filter experiments to starred
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/constants.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
Labels: product

#2171 Add shortcut to sort experiments by starred
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/sortBy/constants.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
Labels: product

#2168 Rename experiments columns tree test file
  extension/src/test/suite/experiments/columns/tree.test.ts
Labels: 🏠 housekeeping

#2173 Revert end to end tests back to insiders
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#2180 Larger drop zones when dragging a plot to another section
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/dragDropSlice.ts
Labels: bug

#2191 Left align timestamp column text
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#2187 Handle dep being added under the current commit
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/model/index.test.ts
Labels: bug

#2186 Add select python interpreter option to setup workspace toast message
  extension/resources/walkthrough/install-dvc.md
  extension/src/extensions/python.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/vscode/response.ts
Labels: product

#2133 Update table styles
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2197 Improve table styles
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: bug

#2200 Do not retry CLI process when unexpected error is received
  extension/src/cli/constants.ts
  extension/src/cli/reader.test.ts
  extension/src/cli/reader.ts
  extension/src/cli/retry.test.ts
  extension/src/cli/retry.ts
  extension/src/experiments/data/collect.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/tree.ts
Labels: bug

#2202 Handle newly introduced deps (before dvc commit)
  extension/src/cli/reader.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/model/index.test.ts
  extension/src/test/fixtures/expShow/uncommittedDeps.ts
  extension/src/util/string.ts
Labels: bug

#2203 Fix experiment table live updates in non-checkpoint experiments
  extension/src/data/index.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/data/collect.ts
  extension/src/experiments/data/index.ts
Labels: bug

#2204 Fix partially hidden header context menus
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#2207 Bump min tested DVC version to 2.18.1
  demo/requirements.txt
  extension/src/cli/constants.ts
Labels: 🏠 housekeeping

#2209 Show min tested version in toast warning message
  extension/src/cli/version.ts
Labels: product

#2212 Fix sticky workspace row obscuring branch
  webview/src/experiments/components/table/TableHead.tsx
Labels: bug

#2206 Make drop zones larger when dragging in the same section
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/util.ts
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DropTarget.tsx
  webview/src/util/array.ts
Labels: bug

#2214 Disable selection on resize
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#2216 Add a copy button for comparison table rows
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/test/selection.ts
Labels: product

#2198 Update cell hover styles
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: bug

#2219 Share an experiment from context menus
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/git.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Row.tsx
Labels: product

#2221 Share an experiment from command palette
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#2227 Replace vary with modify in variable names
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/table/Row.tsx
Labels: 🏠 housekeeping

#2228 Remove experiments from star/unstar text in experiments table
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Row.tsx
Labels: 🏠 housekeeping

#2225 Add Git cli calls into output channel
  extension/src/cli/command.test.ts
  extension/src/cli/command.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/error.ts
  extension/src/cli/executor.ts
  extension/src/cli/git/constants.ts
  extension/src/cli/git/executor.ts
  extension/src/cli/git/index.ts
  extension/src/cli/git/options.ts
  extension/src/cli/git/reader.ts
  extension/src/cli/index.ts
  extension/src/cli/options.test.ts
  extension/src/cli/options.ts
  extension/src/cli/reader.ts
  extension/src/cli/runner.ts
  extension/src/commands/external.ts
  extension/src/commands/internal.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/data/constants.ts
  extension/src/experiments/data/index.ts
  extension/src/extension.ts
  extension/src/git.ts
  extension/src/repository/commands/index.ts
  extension/src/repository/commands/register.ts
  extension/src/repository/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/sourceControlManagement.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/suite/status.test.ts
  extension/src/test/suite/util.ts
  extension/src/test/suite/vscode/outputChannel.test.ts
Labels: product

#2233 Add test utils for dealing with private class methods
  extension/src/test/suite/cli/runner.test.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/fileSystem/tree.test.ts
  extension/src/test/suite/repository/sourceControlManagement.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#2236 Move integration test files into new structure
  extension/src/test/suite/cli/dvc/cwd.test.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
Labels: 🏠 housekeeping

#2237 Add commit and share experiment to context menus
  extension/.prettierignore
  extension/package.json
  extension/package.nls.json
  extension/src/cli/git/constants.ts
  extension/src/cli/git/executor.test.ts
  extension/src/cli/git/executor.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Row.tsx
Labels: product

#2250 Split up `TableHeader.tsx`
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/TableHeaderCell.tsx
  webview/src/experiments/components/table/TableHeaderCellContents.tsx
Labels: 🏠 housekeeping

#2245 Switch experiment sharing to progress api
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.ts
  extension/src/vscode/toast.ts
Labels: product

#2249 Show spinner in the status bar when extension is running Git
  extension/src/extension.ts
Labels: bug

#2261 Bump min tested DVC version to 2.20.1
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2259 Add commit and share experiment command to the palette
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#2257 Display the smoothness slider correctly
  extension/src/test/fixtures/plotsDiff/template/smoothTemplatePlot.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/stories/Plots.stories.tsx
Labels: bug

#2264 Split up `Cell.tsx` and `Row.tsx` files
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: 🏠 housekeeping

#2239 Make timestamp column hideable and draggable
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/columns/quickPick.ts
  extension/src/experiments/columns/tree.test.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/status/index.test.ts
  extension/src/experiments/model/status/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/columns.ts
  extension/src/test/fixtures/expShow/dataTypes.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/test/fixtures/expShow/rows.ts
  turbo.json
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/TableHeaderCell.tsx
  webview/src/test/sort.ts
Labels: product

#2272 Make column `parentPath` optional
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/columns/tree.test.ts
  extension/src/experiments/webview/contract.ts
  webview/src/experiments/hooks/useColumnOrder.ts
Labels: 🏠 housekeeping

#2269 Rename "Timestamp" column label to "Created"
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/status/index.test.ts
  extension/src/experiments/model/status/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/dataTypes.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/test/fixtures/expShow/rows.ts
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/TableHeader.tsx
Labels: product

#2284 Remove leftover file for section renaming
  webview/src/plots/components/SectionRenamer.tsx
Labels: 🏠 housekeeping

#2285 Review when plot sections should collapse
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/util/strings.ts
Labels: product

#2286 Move adding listeners to useLayoutEffect
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
Labels: 🏠 housekeeping

#2290 Show empty state when final comparison plot is de-selected
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
Labels: bug

#2294 Make the first cells of selected rows sticky
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#2289 Improve table styles
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2292 Dispatch publish extension action on merge of update version and CHANGELOG for release PR
  .github/workflows/create-release-pr.yml
  .github/workflows/publish.yml
  .prettierignore
Labels: 🏠 housekeeping

#2295 Persist the order of the comparison table rows
  extension/src/persistence/constants.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/util/array.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/util/objects.ts
Labels: product

#2271 Comparison table rows drag and drop
  extension/src/persistence/constants.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/util/array.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/comparisonTable/RowDropTarget.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DropTarget.tsx
  webview/src/shared/components/dragDrop/util.ts
  webview/src/test/dragDrop.ts
  webview/src/util/objects.ts
Labels: product, make release go now

#2304 Only drag rows not single imagges
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
Labels: bug

#2293 Give option to sort or filter by Created timestamp
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/quickPick.ts
  extension/src/experiments/model/filterBy/date.test.ts
  extension/src/experiments/model/filterBy/date.ts
  extension/src/experiments/model/filterBy/index.test.ts
  extension/src/experiments/model/filterBy/index.ts
  extension/src/experiments/model/filterBy/quickPick.test.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/util/date.test.ts
  extension/src/util/date.ts
  extension/src/vscode/inputBox.ts
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#2305 Improve table column resizing styles
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/TableHeaderCell.tsx
  webview/src/experiments/components/table/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#2091 Use new data status command
  .vscode/settings.json
  demo/requirements.txt
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/options.test.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/fileSystem/util.ts
  extension/src/repository/constants.ts
  extension/src/repository/data/index.ts
  extension/src/repository/decorationProvider.test.ts
  extension/src/repository/decorationProvider.ts
  extension/src/repository/index.ts
  extension/src/repository/model/collect.test.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/repository/sourceControlManagement.test.ts
  extension/src/repository/sourceControlManagement.ts
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/fileSystem/tree.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/util/path.ts
Labels: product

#2151 Refine data status consumption
  extension/package.json
  extension/src/cli/dvc/reader.ts
  extension/src/repository/decorationProvider.test.ts
  extension/src/repository/decorationProvider.ts
  extension/src/repository/model/collect.test.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/repository/sourceControlManagement.ts
Labels: product

#2266 Bump min version of DVC to 2.21.0 (data status)
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping
