Repository iterative/vscode-dvc, pull requests merged in 2022-06, with the labels that each got.

#1876 Review and update the walkthrough
  extension/package.json
  extension/resources/walkthrough/command-palette.md
  extension/resources/walkthrough/dvc-learn-more.md
  extension/resources/walkthrough/dvc-tracked-files.md
  extension/resources/walkthrough/experiments-table.md
  extension/resources/walkthrough/images/available-commands-command-palette.png
  extension/resources/walkthrough/images/dvc-tracked-explorer.png
  extension/resources/walkthrough/images/dvc-tracked-scm.png
  extension/resources/walkthrough/images/experiments-table-context-menus.png
  extension/resources/walkthrough/images/experiments-table-from-side-bar.png
  extension/resources/walkthrough/images/experiments-table.png
  extension/resources/walkthrough/images/install-dvc-setup-wizard.png
  extension/resources/walkthrough/images/install-dvc-status-bar-detected.png
  extension/resources/walkthrough/images/live-plots-updates.gif
  extension/resources/walkthrough/images/plots-data-series.png
  extension/resources/walkthrough/images/plots-dump-image.png
  extension/resources/walkthrough/images/plots-dump-with-dvclive.png
  extension/resources/walkthrough/images/plots-dump-with-open-file.png
  extension/resources/walkthrough/images/plots-experiments-view-icon.png
  extension/resources/walkthrough/images/plots-images.png
  extension/resources/walkthrough/images/plots-plots-view-icon.png
  extension/resources/walkthrough/images/plots-trends.png
  extension/resources/walkthrough/images/run-experiments-command-palette.png
  extension/resources/walkthrough/images/run-experiments-params-buttons.png
  extension/resources/walkthrough/images/run-experiments-table-buttons.png
  extension/resources/walkthrough/images/setup-project-dump-metrics.png
  extension/resources/walkthrough/images/setup-project-dvc-yaml-example.png
  extension/resources/walkthrough/images/setup-project-dvclive-metrics.png
  extension/resources/walkthrough/images/view-container-columns.png
  extension/resources/walkthrough/images/view-container-experiments.png
  extension/resources/walkthrough/images/view-container-filter.png
  extension/resources/walkthrough/images/view-container-plots.png
  extension/resources/walkthrough/images/view-container-show.png
  extension/resources/walkthrough/images/view-container-sort.png
  extension/resources/walkthrough/images/view-container-support.png
  extension/resources/walkthrough/images/view-container-welcome.png
  extension/resources/walkthrough/install-dvc.md
  extension/resources/walkthrough/live-plots.md
  extension/resources/walkthrough/output-channel.md
  extension/resources/walkthrough/plots.md
  extension/resources/walkthrough/run-experiments.md
  extension/resources/walkthrough/setup-project.md
  extension/resources/walkthrough/setup-workspace.md
  extension/resources/walkthrough/source-control-management.md
  extension/resources/walkthrough/tracked-explorer.md
  extension/resources/walkthrough/troubleshoot.md
  extension/resources/walkthrough/view-container.md
Labels: product, A: docs

#1894 hotfix: VS Code badges in README
  README.md
Labels: bug

#1905 Fix Windows repo file watcher using RelativePattern
  extension/src/repository/data/index.ts
Labels: bug

#1901 Upgrade @vscode/test-electron
  extension/package.json
  extension/src/test/suite/cli/runner.test.ts
  yarn.lock
Labels: 🏠 housekeeping

#1899 Remove unused SVGs
  extension/resources/alt-banner.svg
  extension/resources/banner.svg
Labels: 🏠 housekeeping

#1900 Improve reset the workspace SCM command
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/git.ts
  extension/src/repository/commands/register.ts
  extension/src/repository/data/index.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/sourceControlManagement.test.ts
  extension/src/test/suite/repository/util.ts
Labels: product

#1909 Fix (local) intermittent test failures
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#1914 Fix test timeout failures
  extension/src/test/suite/cli/runner.test.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#1915 Improve reset the workspace SCM command
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/git.ts
  extension/src/repository/commands/register.ts
  extension/src/repository/data/index.ts
  extension/src/repository/decorationProvider.ts
  extension/src/repository/index.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/repository/sourceControlManagement.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/sourceControlManagement.test.ts
  extension/src/test/suite/repository/util.ts
Labels: product

#1921 Fix DVC cwd for Windows
  extension/src/cli/cwd.ts
  extension/src/cli/options.ts
  extension/src/test/suite/cli/cwd.test.ts
Labels: bug

#1941 Simplify import of icons
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/plots/components/DropTarget.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/DropTarget.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/shared/components/Icon.tsx
  webview/src/shared/components/button/IconButton.tsx
  webview/src/shared/components/button/RefreshButton.tsx
  webview/src/shared/components/button/StartButton.tsx
  webview/src/shared/components/dragDrop/GripIcon.tsx
  webview/src/shared/components/iconMenu/IconMenu.test.tsx
  webview/src/shared/components/iconMenu/IconMenuItem.tsx
  webview/src/shared/components/modal/Modal.tsx
  webview/src/shared/components/selectMenu/SelectMenuOption.tsx
  webview/src/stories/ContextMenu.stories.tsx
  webview/src/stories/IconMenu.stories.tsx
Labels: 🏠 housekeeping

#1832 Adding Redux to plots
  extension/src/plots/webview/contract.ts
  webview/package.json
  webview/src/plots/actions.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/PlotsSizeContext.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/plotDataStore.ts
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/plots/constants.ts
  webview/src/plots/hooks/useAppReducer.ts
  webview/src/plots/index.tsx
  webview/src/plots/store.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/util/objects.ts
  yarn.lock
Labels: 🏠 housekeeping

#1945 Remove clear data action
  webview/src/plots/actions.ts
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/plots/constants.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#1944 Use Redux for drag and drop state
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/plots/store.ts
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/dragDropSlice.ts
  webview/src/stories/ComparisonTable.stories.tsx
Labels: 🏠 housekeeping

#1951 Show DVC roots in tracked tree when there is more than one DVC project in the workspace
  extension/src/fileSystem/tree.test.ts
  extension/src/fileSystem/tree.ts
Labels: bug

#1952 Show DVC root in tracked tree if there is only a single project nested inside of the workspace
  extension/src/fileSystem/tree.test.ts
  extension/src/fileSystem/tree.ts
Labels: bug

#1953 Show errors when interacting with the CLI from the experiments webview or tree
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: bug

#1950 Star experiments in table
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/persistence/constants.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/components/icons/StarEmpty.tsx
  webview/src/shared/components/icons/StarFull.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/shared/components/messagesMenu/MessagesMenu.tsx
  webview/src/shared/components/messagesMenu/MessagesMenuOption.tsx
  webview/src/shared/components/messagesMenu/styles.module.scss
Labels: product

#1959 Prime the repository for Renovate
  .github/workflows/continuous-integration.yml
  extension/.eslintrc.js
  extension/package.json
  extension/src/cli/executor.test.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/repository/model/index.ts
  extension/src/telemetry/index.test.ts
  extension/src/telemetry/index.ts
  extension/src/test/suite/cli/runner.test.ts
  extension/src/util/stdout.ts
  package.json
  webview/package.json
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/webviewSlice.ts
  yarn.lock
Labels: 🏠 housekeeping
