Repository iterative/vscode-dvc, pull requests merged in 2022-11, with the labels that each got.

#2715 Fixes infinite loop in plots when workspace only is selected
  extension/src/plots/data/index.ts
Labels: bug, A: plots, priority-p0

#2706 Add tooltips to experiments tree
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPicks.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/model/util.ts
  extension/src/experiments/workspace.ts
  extension/src/test/util/jest/index.ts
Labels: product

#2573 Update the DVC: Get Started / Plots Dashboard
  extension/resources/walkthrough/images/click-the-circle-beside-experiment-name.png
  extension/resources/walkthrough/plots.md
Labels: product

#2738 Check hidden status when getting first three exp table column order
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/workspace.ts
  extension/src/path/selection/model.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/util/jest/index.ts
Labels: bug

#2748 Fix unit tests for non en-US timezones
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/tree.test.ts
Labels: 🏠 housekeeping

#2750 Use JSON5 library to parse non-standard JSON
  extension/package.json
  extension/src/cli/dvc/reader.ts
  extension/src/util/json.test.ts
  extension/src/util/json.ts
Labels: bug

#2753 Update scheduled CLI test to match expected demo project output
  extension/src/test/cli/dataStatus.test.ts
Labels: 🏠 housekeeping

#2643 Refactor context-menu options in table header
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/webview/messages.ts
  extension/src/path/selection/model.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
Labels: enhancement, 🏠 housekeeping, A: table

#2759 Make plots ribbon sticky on scroll
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/components/webviewWrapper/WebviewWrapper.tsx
  webview/src/shared/components/webviewWrapper/styles.module.scss
Labels: product, A: plots

#2760 Add "views" section to sidebar
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/context.ts
  extension/src/webview/factory.ts
  extension/src/webview/index.ts
  extension/src/webview/repository.ts
  extension/src/webview/workspace.ts
Labels: product

#2785 Fix map on undefined is path doesn't exist in rev
  extension/src/plots/model/collect.ts
Labels: bug, priority-p0

#2783 Add resolution for loader-utils
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#2791 Load projects inside multi-root workspaces
  extension/src/setup.ts
Labels: bug

#2795 Check availability and compatibility on DVC projects in multi root workspaces
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
Labels: bug

#2805 Patch experiment with checkpoints not having a name
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
Labels: bug

#2806 Fix webview test warnings
  webview/src/experiments/components/App.test.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#2811 Stabilize plot paths
  extension/src/plots/model/collect.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.ts
Labels: bug

#2813 Match the way that undefined/numeric experiment column values are shown in the table in tooltips and quick picks
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/util.ts
  webview/src/experiments/util/buildDynamicColumns.tsx
Labels: product

#2818 Fix scheduled CLI output test by updating expected demo project output
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/cli/plotsDiff.test.ts
Labels: 🏠 housekeeping

#2820 Match open webviews welcome view button titles with command palette actions
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/telemetry/constants.ts
  extension/src/test/e2e/extension.test.ts
Labels: 🏠 housekeeping

#2593 Add missing "Hide Column" option to the other headers
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/webview/messages.ts
  extension/src/path/selection/model.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
Labels: enhancement, A: table

#2823 Add resolution for fastify
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#2747 Resizing plots horizontally
  .eslintrc.js
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/Resizer.tsx
  webview/src/plots/components/SizePicker.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/util.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/plots/hooks/useNbItemsPerRow.ts
  webview/src/plots/hooks/useResize.ts
  webview/src/shared/components/webviewWrapper/useThemeVariables.ts
  webview/src/shared/variables.scss
  webview/src/test/mouseEventsWithCoordinates.ts
Labels: product

#2826 Reduce renovate noise
  renovate.json
Labels: 🏠 housekeeping

#2833 Fix aspect ratio of multi view plots
  webview/src/plots/components/styles.module.scss
Labels: bug

#2832 Delay creation of plots to remove optional logic
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/workspace.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/webview/workspace.ts
  extension/src/workspace/index.ts
Labels: 🏠 housekeeping

#2838 Remove auto-merge component from renovate config (does not work)
  renovate.json
Labels: 🏠 housekeeping

#2850 Add styled divs to maintain table story snapshot parity
  webview/src/stories/Table.stories.tsx
Labels: 🏠 housekeeping

#2852 Do not process CLI errors thrown by plots diff
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.ts
  extension/src/data/index.ts
  extension/src/plots/data/index.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
Labels: bug

#2841 Add progress ring to plots ribbon while data is loading
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/util/array.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/stories/Ribbon.stories.tsx
Labels: product

#2859 Separate comparison table and plot ribbon revision orders
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/stories/ComparisonTable.stories.tsx
Labels: 🏠 housekeeping

#2864 Open plots in split view when request sent from table
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: product

#2862 Do not snapshot story with progress rings
  webview/src/stories/Ribbon.stories.tsx
Labels: 🏠 housekeeping

#2863 Match VS Code version of @types/node
  extension/package.json
  renovate.json
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping
