Repository iterative/vscode-dvc, pull requests merged in 2022-09, with the labels that each got.

#2267 Consume unknown from data status
  .vscode/settings.json
  extension/package.json
  extension/src/cli/dvc/reader.ts
  extension/src/repository/constants.ts
  extension/src/repository/decorationProvider.test.ts
  extension/src/repository/decorationProvider.ts
  extension/src/repository/model/collect.test.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/suite/repository/index.test.ts
Labels: product

#2299 Bump min version of DVC to 2.23.0 (--with-dirs removed from data status)
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
Labels: 🏠 housekeeping

#2300 Remove retries from reader (all commands now lockless)
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/dvc/retry.test.ts
  extension/src/cli/dvc/retry.ts
Labels: product

#2280 Account for exp show returning an empty object
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
Labels: bug

#2314 Bump min version of DVC to 2.24.0 (patch windows paths in data status)
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2301 Show data status errors in DVC Tracked tree
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/experiments/decorationProvider.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/fileSystem/tree.test.ts
  extension/src/fileSystem/tree.ts
  extension/src/repository/data/index.ts
  extension/src/repository/errorDecorationProvider.ts
  extension/src/repository/index.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/error.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/repository/scmDecorationProvider.test.ts
  extension/src/repository/scmDecorationProvider.ts
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/util/stdout.test.ts
  extension/src/util/stdout.ts
Labels: product

#2320 Fix drag leave of top and bottom sections
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/hooks/useDeferedDragLeave.ts
  webview/src/test/dragDrop.ts
Labels: bug

#2316 Fix bugs in table styles
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: bug

#2330 Consolidate use of decoration providers with tree views
  extension/src/experiments/decorationProvider.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/decorationProvider.ts
  extension/src/experiments/model/filterBy/tree.ts
  extension/src/experiments/model/sortBy/tree.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/fileSystem/tree.test.ts
  extension/src/fileSystem/tree.ts
  extension/src/path/selection/tree.ts
  extension/src/repository/errorDecorationProvider.ts
  extension/src/repository/index.ts
  extension/src/repository/model/decorationProvider.ts
  extension/src/tree/errorDecorationProvider.ts
  extension/src/tree/index.ts
  extension/src/vscode/tree.ts
Labels: 🏠 housekeeping

#2331 Move DVC Tracked tree into repository directory structure
  extension/src/extension.ts
  extension/src/repository/model/tree.test.ts
  extension/src/repository/model/tree.ts
  extension/src/test/suite/repository/model/tree.test.ts
Labels: 🏠 housekeeping

#2341 Make first cell text contents selectable
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/util/props.ts
Labels: bug

#2346 Remove extra sending of data to webview on change of star selection
  extension/src/experiments/webview/messages.ts
Labels: 🏠 housekeeping

#2344 Truncate long plot titles
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/util.ts
Labels: bug

#2353 Match tooltip styles to VS Code
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/contextMenu/ContextMenu.tsx
  webview/src/shared/components/iconMenu/IconMenu.tsx
  webview/src/shared/components/tooltip/Tooltip.tsx
  webview/src/shared/components/tooltip/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2355 Always show context menu on right click
  webview/src/experiments/components/App.test.tsx
  webview/src/shared/components/contextMenu/ContextMenu.tsx
Labels: bug

#2354 Dismiss tooltip/context menus on Escape
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/TableHeaderCellContents.tsx
  webview/src/plots/components/App.test.tsx
  webview/src/shared/components/tooltip/Tooltip.tsx
Labels: bug

#2363 Ensure welcome screen is not shown when only one column is provided
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
Labels: bug

#2366 Fix zoomed in plot overflow
  webview/src/plots/components/styles.module.scss
Labels: bug

#2367 Update table indicators and chevrons/stars styles
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2365 Truncate all long titles inside of plots
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/util.ts
  webview/src/util/objects.ts
Labels: bug

#2377 Move experiment table context menus to right-start
  webview/src/shared/components/contextMenu/ContextMenu.tsx
Labels: product

#2376 Ensure table indicators do not overlap with experiment column title
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/TableHead.tsx
  webview/src/experiments/components/table/TableHeader.tsx
  webview/src/experiments/components/table/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/columns.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: bug

#2381 Fix overflowing comparison table texts
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: bug

#2384 Update cell hint styles and context menu position
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellHintTooltip.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/components/contextMenu/ContextMenu.tsx
  webview/src/shared/components/tooltip/Tooltip.tsx
  webview/src/stories/Table.stories.tsx
Labels: product

#2388 Add plotting actions to experiments table context menu
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/plots/commands/register.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  extension/src/webview/workspace.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: product

#2391 Update selected row foreground
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#2396 Move vega title truncation into the extension
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/checkpointPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/plots/util.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/plotDataStore.ts
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/util.ts
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#2404 Use webpack's development mode to build webview for testing
  package.json
  turbo.json
  webview/.storybook/main.ts
  webview/package.json
Labels: 🏠 housekeeping

#2409 Remove unused SVGs
  extension/resources/dark/loading-spin.svg
  extension/resources/light/loading-spin.svg
Labels: 🏠 housekeeping

#2410 Exclude queued experiments from select experiments for plots quick pick
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
Labels: bug

#2425 Remove extra background color from the table view
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/variables.scss
Labels: A: table, product

#2428 Bump min tested version of DVC to 2.26.2
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2440 Bump min tested version of DVC to 2.27.2
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2439 Update `view/title` commands to account for VS Code change
  extension/package.json
  extension/src/experiments/commands/register.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/messages.ts
  extension/src/plots/commands/register.ts
  extension/src/tree/index.ts
  extension/src/vscode/context.ts
Labels: bug

#2392 Multiple commits in the experiments table
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/filterBy/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/test/fixtures/expShow/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/util/jest/index.ts
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#2451 Move remaining data update watchers to RelativePatterns
  extension/src/data/index.ts
  extension/src/fileSystem/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
Labels: 🏠 housekeeping

#2436 Add config for updating max amount of table head layers
  README.md
  extension/package.json
  extension/package.nls.json
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/columns/consts.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/index.ts
  extension/src/vscode/config.ts
Labels: product

#2460 Turn off language server until it is fixed
  extension/src/extension.ts
Labels: bug

#2470 Remove coverage for prettier
  languageServer/.prettierignore
Labels: 🏠 housekeeping, A: lsp

#2469 Add webpack to languageServer (1/3)
  extension/src/extension.ts
  languageServer/package.json
  languageServer/webpack.config.ts
  yarn.lock
Labels: bug, A: lsp

#2445 Send initial YAML and JSON files right after language client starts (2/3)
  extension/src/lspClient/languageClient.ts
  languageServer/src/LanguageServer.ts
  languageServer/src/test/definitions.test.ts
  languageServer/src/test/utils/sendTheseFilesToServer.ts
Labels: product, A: lsp

#2462 Check for global install of CLI after python install not found
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/dvc/runner.ts
  extension/src/config.ts
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
  extension/src/test/suite/config.test.ts
  extension/src/test/suite/extension.test.ts
Labels: bug

#2463 Account for exp show returning extra data in CLI output tests
  extension/src/test/cli/expShow.test.ts
Labels: bug

#2471 Add tests for column depth configuration
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/columns/consts.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/test/fixtures/expShow/deeplyNested.ts
  extension/src/vscode/config.ts
Labels: 🏠 housekeeping

#2481 Cleanup after drag and drop
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
Labels: bug

#2403 Render flexible plots
  .vscode/settings.json
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/multiSource/collect.test.ts
  extension/src/plots/multiSource/collect.ts
  extension/src/plots/multiSource/constants.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  turbo.json
  webview/src/plots/components/ZoomedInPlot.tsx
Labels: product

#2452 Add flexible plots legends to plots tree
  extension/resources/plots/circle.svg
  extension/resources/plots/diamond.svg
  extension/resources/plots/square.svg
  extension/resources/plots/stroke-dash-1-0.svg
  extension/resources/plots/stroke-dash-1-1.svg
  extension/resources/plots/stroke-dash-2-1.svg
  extension/resources/plots/stroke-dash-4-2.svg
  extension/resources/plots/stroke-dash-4-4.svg
  extension/resources/plots/stroke-dash-8-4.svg
  extension/resources/plots/stroke-dash-8-8.svg
  extension/resources/plots/triangle.svg
  extension/src/experiments/columns/model.ts
  extension/src/experiments/columns/tree.ts
  extension/src/path/selection/model.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/index.ts
  extension/src/plots/model/index.ts
  extension/src/plots/multiSource/constants.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/paths/tree.test.ts
  extension/src/plots/paths/tree.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/resourceLocator.ts
Labels: product

#2489 Fix comparison table row copy button
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: bug

#2487 Do not walk unnecessary keys in truncate titles
  extension/src/plots/vega/util.ts
Labels: 🏠 housekeeping

#2486 Remove erroneous shape from vertical on hover line when shape dimension is added
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/test/fixtures/plotsDiff/templates/multiSource.ts
Labels: bug

#2488 Bump min tested version of DVC to 2.28.0
  demo/requirements.txt
  extension/src/cli/dvc/constants.ts
Labels: 🏠 housekeeping

#2493 Stabilize e2e tests
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#2490 Add tooltip to comparison table row path
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
Labels: bug

#2491 Make the comparison table row path take available space
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: bug

#2500 Use a variable for tooltip delays
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/CellHintTooltip.tsx
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/shared/components/tooltip/Tooltip.tsx
  webview/src/stories/Table.stories.tsx
Labels: 🏠 housekeeping

#2505 Turn off language server again
  demo/dvc.yaml
  extension/src/extension.ts
Labels: bug
