Repository iterative/vscode-dvc, pull requests merged in 2022-12, with the labels that each got.

#2861 Add webview for when dvc is not available or not initialized
  extension/package.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/telemetry/constants.ts
  extension/src/webview/constants.ts
  extension/src/webview/factory.ts
  webview/.eslintrc.js
  webview/index.d.ts
  webview/index.js
  webview/src/getStarted/components/App.tsx
  webview/src/getStarted/index.tsx
  webview/webpack.config.ts
Labels: product

#2865 Add loading state for sections and images to plots webview
  extension/src/plots/webview/contract.ts
  webview/__mocks__/@vscode/webview-ui-toolkit/react.tsx
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/LoadingSection.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/stories/ComparisonTable.stories.tsx
Labels: product

#2872 Watch workspace and filter results before calling for data updates
  extension/src/data/index.ts
  extension/src/experiments/data/collect.ts
  extension/src/experiments/data/index.ts
  extension/src/plots/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/data/index.test.ts
Labels: 🏠 housekeeping

#2876 Improve table header DnD
  .vscode/launch.json
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/columns.test.ts
  webview/src/experiments/util/columns.ts
  webview/src/shared/components/iconMenu/IconMenu.tsx
  webview/src/shared/variables.scss
Labels: enhancement, A: table, product

#2877 Stabilise colors of running experiments
  extension/src/experiments/index.ts
  extension/src/experiments/model/accumulator.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/webview/contract.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  webview/src/experiments/components/App.test.tsx
Labels: product

#2888 Prevent toggle selection of checkpoint experiment running in the workspace
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
Labels: bug

#2897 Improve stability of e2e tests for new VS Code release
  extension/src/test/e2e/pageObjects/baseWebview.ts
Labels: 🏠 housekeeping

#2895 Move from vsce to @vscode/vsce
  extension/package.json
  yarn.lock
Labels: 🏠 housekeeping

#2905 Split turbo cache between workflows
  .github/workflows/cross-platform-test.yml
  .github/workflows/end-to-end-test.yml
Labels: 🏠 housekeeping

#2906 Update scheduled cli test
  extension/src/test/cli/dataStatus.test.ts
Labels: 🏠 housekeeping

#2894 Dynamic Get Started webview
  extension/package.json
  extension/src/cli/dvc/discovery.ts
  extension/src/extension.ts
  extension/src/getStarted/index.ts
  extension/src/getStarted/webview/contract.ts
  extension/src/getStarted/webview/messages.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/setupUtil.ts
  extension/src/test/suite/getStarted/index.test.ts
  extension/src/test/suite/getStarted/util.ts
  extension/src/test/suite/util.ts
  extension/src/webview/contract.ts
  webview/src/getStarted/components/App.test.tsx
  webview/src/getStarted/components/App.tsx
  webview/src/getStarted/components/CliUnavailable.tsx
  webview/src/getStarted/components/ProjectUninitialized.tsx
  webview/webpack.config.ts
Labels: product

#2923 Use DVCLive signal file to indicate that an experiment is running in the workspace
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/processExecution.test.ts
  extension/src/processExecution.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/fileSystem/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/util/number.test.ts
  extension/src/util/number.ts
  yarn.lock
Labels: product, A: onboarding

#2928 Recheck for global CLI becoming available
  extension/src/cli/dvc/discovery.ts
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/setupUtil.ts
  extension/src/test/suite/extension.test.ts
Labels: bug

#2915 Only show plots which are available for selected revisions
  extension/src/experiments/columns/model.ts
  extension/src/path/selection/model.ts
  extension/src/path/selection/quickPick.test.ts
  extension/src/plots/index.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/GetStarted.tsx
Labels: product

#2934 Prevent unnecessary CLI calls in the integration test suite
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/processManager.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
  extension/src/test/suite/getStarted/index.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/processManager.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/suite/util.ts
  extension/src/util/disposable.test.ts
  extension/src/util/disposable.ts
  extension/src/workspace/index.ts
Labels: 🏠 housekeeping

#2933 Update renovate config
  renovate.json
Labels: 🏠 housekeeping

#2932 Update plots empty states to reflect dynamic nature of available plots
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/webviewSlice.ts
  webview/src/stories/Plots.stories.tsx
Labels: product

#2935 Fix cleanup on merging drag and drop groups
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
Labels: bug

#2938 Revert e2e tests back on to insiders
  extension/src/test/e2e/wdio.conf.ts
Labels: bug

#2924 Add columns tooltip to plots ribbon
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/model/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/styles.module.scss
Labels: product

#2939 Do not rely on number of call to execute process stub in integration tests
  extension/src/test/suite/repository/sourceControlManagement/index.test.ts
Labels: 🏠 housekeeping

#2954 Move Views sidebar section to the top
  extension/package.json
Labels: product

#2948 Ensure that all watcher's listeners are disposed
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/extension.ts
  extension/src/fileSystem/data/index.ts
  extension/src/fileSystem/watcher.test.ts
  extension/src/fileSystem/watcher.ts
  extension/src/repository/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#2927 Show a screen when there is no data in the project
  extension/package.json
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/getStarted/index.ts
  extension/src/getStarted/webview/contract.ts
  extension/src/getStarted/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/getStarted/util.ts
  extension/src/webview/constants.ts
  webview/jest.config.js
  webview/package.json
  webview/rawLoaderTransformer.js
  webview/src/getStarted/components/App.test.tsx
  webview/src/getStarted/components/App.tsx
  webview/src/getStarted/components/NoData.tsx
  webview/src/getStarted/snippets/huggingFace.py
  webview/src/getStarted/snippets/keras.py
  webview/src/getStarted/snippets/pyTorch.py
  webview/src/getStarted/snippets/pythonApi.py
  webview/src/py.d.ts
  webview/src/shared/components/codeBlock/CodeBlock.tsx
  webview/src/shared/components/codeBlock/styles.module.scss
  webview/src/shared/components/codeSlider/CodeSlider.tsx
  webview/src/shared/components/codeSlider/styles.module.scss
  webview/src/shared/components/emptyState/styles.module.scss
  webview/webpack.config.ts
  yarn.lock
Labels: product

#2968 Close setup webview when all actions have been completed
  extension/src/getStarted/webview/messages.ts
  extension/src/test/suite/getStarted/index.test.ts
Labels: product

#2967 Simplify Setup the Workspace by removing manual option when Python extension is installed
  README.md
  extension/src/cli/dvc/discovery.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/test/suite/extension.test.ts
  extension/src/vscode/response.ts
Labels: product

#2957 Temporarily remove VS Marketplace badges
  README.md
Labels: 🏠 housekeeping

#2969 Add environment selection information to the DVC status bar item
  extension/src/extension.ts
  extension/src/status.ts
  extension/src/test/suite/status.test.ts
Labels: product

#2977 Left align code block text on the no data setup screen
  webview/src/shared/components/codeBlock/styles.module.scss
  webview/src/shared/components/codeSlider/styles.module.scss
  webview/src/stories/NoData.stories.tsx
Labels: bug

#2971 Refactor `getDataFromColumnPath` logic
  extension/src/experiments/model/quickPicks.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/model/util.ts
  extension/src/plots/model/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/util/number.ts
Labels: 🏠 housekeeping

#2974 Enable user to move from Global to Auto without reloading the window
  extension/src/config.ts
  extension/src/extension.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
Labels: bug

#2973 Open experiments automatically once setup is done
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/getStarted/index.ts
  extension/src/getStarted/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/getStarted/index.test.ts
  extension/src/test/suite/getStarted/util.ts
  extension/src/webview/contract.ts
  webview/src/getStarted/components/App.test.tsx
  webview/src/getStarted/components/App.tsx
Labels: product

#2982 Rename getStarted to setup
  extension/package.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
  extension/src/webview/constants.ts
  extension/src/webview/contract.ts
  extension/src/webview/repository.ts
  webview/.eslintrc.js
  webview/index.d.ts
  webview/index.js
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/CliUnavailable.tsx
  webview/src/setup/components/NoData.tsx
  webview/src/setup/components/ProjectUninitialized.tsx
  webview/src/setup/index.tsx
  webview/src/setup/snippets/huggingFace.py
  webview/src/setup/snippets/keras.py
  webview/src/setup/snippets/pyTorch.py
  webview/src/setup/snippets/pythonApi.py
  webview/src/stories/NoData.stories.tsx
  webview/webpack.config.ts
Labels: 🏠 housekeeping

#2983 Adjust formatting on table cell long numbers
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/util.ts
  extension/src/util/number.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/components/tooltip/Tooltip.tsx
  webview/src/util/number.ts
Labels: product

#2944 Provide option to auto-install DVC if unavailable
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/extensions/python.ts
  extension/src/fileSystem/index.ts
  extension/src/python/index.ts
  extension/src/setup/autoInstall.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/autoInstall.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/CliUnavailable.tsx
  webview/src/stories/CliUnavailable.stories.tsx
Labels: product

#2990 Direct users to setup webview from warning popups
  extension/package.json
  extension/src/cli/dvc/discovery.ts
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup/index.ts
  extension/src/status.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/status.test.ts
  extension/src/vscode/response.ts
  extension/src/vscode/title.ts
Labels: product

#2992 Patch CLI incompatible path for onboarding
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/discovery.ts
  extension/src/cli/dvc/version.test.ts
  extension/src/cli/dvc/version.ts
  extension/src/extension.ts
  extension/src/setup.test.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/util.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/CliIncompatible.tsx
  webview/src/stories/CliIncompatible.stories.tsx
Labels: product

#2989 Update demo project and latest tested CLI version (2.38.1)
  extension/src/cli/dvc/contract.ts
Labels: 🏠 housekeeping

#2988 Get closer to theme inside of code blocks shown on no experiments data screen
  webview/src/shared/components/codeBlock/CodeBlock.tsx
Labels: product

#2996 Initially expand commit entries in the experiments tree
  extension/src/experiments/model/tree.ts
Labels: bug

#3001 Update status bar item
  extension/src/status.ts
  extension/src/test/suite/status.test.ts
Labels: 🏠 housekeeping

#2965 Table DnD cleanup, reset drop zone on leave
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/components/dragDrop/Draggable.tsx
Labels: A: table, product

#3007 Cleanup table dnd code: remove unused slice/group logic
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/store.ts
  webview/src/shared/components/dragDrop/Draggable.tsx
Labels: 🏠 housekeeping, A: table

#3005 Upgrade e2e test dependencies and Mocha
  .husky/pre-commit
  extension/package.json
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/package.json
  extension/src/test/e2e/pageObjects/baseWebview.ts
  extension/src/test/e2e/pageObjects/experimentsWebview.ts
  extension/src/test/e2e/pageObjects/plotsWebview.ts
  extension/src/test/e2e/tsconfig.json
  extension/src/test/e2e/util.ts
  extension/src/test/e2e/wdio.conf.ts
  extension/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: 🏠 housekeeping

#3002 Offer to Git init when there is no DVC project or Git repository
  extension/src/extension.ts
  extension/src/fileSystem/index.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/ProjectUninitialized.tsx
  webview/src/stories/ProjectUninitialized.stories.tsx
Labels: product

#3017 Split setup from extension
  extension/src/cli/dvc/discovery.ts
  extension/src/extension.ts
  extension/src/interfaces.ts
  extension/src/setup.test.ts
  extension/src/setup.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3018 Rename original setup file to runner
  extension/src/cli/dvc/discovery.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/setup/runner.test.ts
  extension/src/setup/runner.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/util.ts
Labels: 🏠 housekeeping

#3023 Simply welcome view inside view container
  extension/package.json
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/CliIncompatible.tsx
  webview/src/stories/CliIncompatible.stories.tsx
Labels: product

#3024 Add periods to setup webview views
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/CliUnavailable.tsx
  webview/src/setup/components/NoData.tsx
  webview/src/setup/components/ProjectUninitialized.tsx
Labels: 🏠 housekeeping

#3025 Add DVC and Git initialization watcher
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/experiments/data/index.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/repository/model/index.ts
  extension/src/repository/model/tree.ts
  extension/src/setup/index.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
Labels: bug

#3026 Integrate walkthrough with setup webview
  extension/package.json
  extension/resources/walkthrough/install-dvc.md
  extension/resources/walkthrough/setup-project.md
Labels: product

#3032 GitHub actions update
  .github/workflows/create-release-pr.yml
  .github/workflows/publish.yml
Labels: 🏠 housekeeping
