Repository iterative/vscode-dvc, pull requests merged in 2023-12, with the labels that each got.

#5054 Handle missing items in drag and drop container
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
Labels: bug

#5049 Improve Studio Token Authentication URI Handler
  extension/src/setup/studio.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/vscode/external.test.ts
  extension/src/vscode/external.ts
Labels: 🏠 housekeeping

#5045 Handle project having experiments with no data
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/setup/index.ts
  extension/src/test/suite/setup/util.ts
Labels: bug

#5071 Cancel Studio Token Request after five minutes
  extension/src/setup/studio.ts
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#5079 Fix flaky cancel token request test
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#5082 Move e2e tests to stable
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#5072 Add commands for updating `studio.url` in DVC configuration
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/data/index.ts
  extension/src/setup/commands/register.ts
  extension/src/setup/index.ts
  extension/src/setup/inputBox.test.ts
  extension/src/setup/inputBox.ts
  extension/src/setup/studio.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/vscode/context.ts
  extension/src/vscode/title.ts
Labels: product

#5084 Bump min version of VS Code to 1.75.0
  extension/package.json
  extension/src/test/suite/vscode/outputChannel.test.ts
  yarn.lock
Labels: bug

#5085 Use resize observer to simplify use get plot
  webview/setup-tests.js
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/vegaLite/ExtendedVegaLite.tsx
  webview/src/plots/hooks/useGetPlot.ts
Labels: 🏠 housekeeping

#5088 Improve studio access token commands
  extension/package.json
  extension/src/setup/index.ts
Labels: 🏠 housekeeping

#5097 Reduce number of plots resize observers
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsGrid.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/hooks/useGetPlot.ts
  webview/src/plots/hooks/useObserveGridDimensions.ts
Labels: 🏠 housekeeping

#5089 Add self-hosted url info in Studio setup section
  extension/src/setup/index.ts
  extension/src/setup/studio.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/dvc/DvcEnvCommandRow.tsx
  webview/src/setup/components/dvc/DvcEnvDetails.tsx
  webview/src/setup/components/dvc/DvcEnvInfoRow.tsx
  webview/src/setup/components/dvc/styles.module.scss
  webview/src/setup/components/shared/DetailsTable.tsx
  webview/src/setup/components/shared/DetailsTableRow.tsx
  webview/src/setup/components/shared/styles.module.scss
  webview/src/setup/components/studio/Connect.tsx
  webview/src/setup/components/studio/Settings.tsx
  webview/src/setup/components/studio/Studio.tsx
  webview/src/setup/state/dvcSlice.ts
  webview/src/setup/state/studioSlice.ts
  webview/src/setup/util/messages.ts
  webview/src/stories/Setup.stories.tsx
Labels: product

#5062 Use hook for drag and drop
  .eslintrc.js
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/DragAndDropGrid.tsx
  webview/src/plots/components/DragAndDropPlot.tsx
  webview/src/plots/components/Grid.tsx
  webview/src/plots/components/NormalGrid.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/AddedSection.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DragDropItem.tsx
  webview/src/shared/components/dragDrop/DragDropItemWithTarget.tsx
  webview/src/shared/components/dragDrop/dragDropSlice.ts
  webview/src/shared/components/dragDrop/util.ts
  webview/src/shared/components/virtualizedGrid/VirtualizedGrid.tsx
  webview/src/shared/hooks/useDeferredDragLeave.ts
  webview/src/shared/hooks/useDragAndDrop.tsx
  webview/src/stories/ComparisonTableHeader.stories.tsx
  webview/src/util/objects.ts
Labels: 🏠 housekeeping

#5113 Add lint rule for one React component per file
  .eslintrc.js
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/ExperimentsTable.tsx
  webview/src/experiments/components/table/CounterBadge.tsx
  webview/src/experiments/components/table/Indicator.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/CellRowAction.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
  webview/src/experiments/components/table/body/ClickableTooltipContent.tsx
  webview/src/experiments/components/table/body/CopyStudioLink.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/body/OnRemote.tsx
  webview/src/experiments/components/table/body/Progress.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/RowExpansionButton.tsx
  webview/src/experiments/components/table/body/StubCell.tsx
  webview/src/experiments/components/table/header/ColumnDragHandle.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/header/WithExpColumnNeedsShadowUpdates.tsx
  webview/src/plots/components/PathHighlight.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/PlotsContent.tsx
  webview/src/plots/components/TooManyPlots.tsx
  webview/src/plots/components/ribbon/RevisionIcon.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/experiments/PythonCodeBlock.tsx
  webview/src/shared/components/copyButton/CopyButton.tsx
  webview/src/shared/components/tooltip/ErrorTooltip.tsx
  webview/src/shared/components/tooltip/ErrorTooltipContent.tsx
Labels: 🏠 housekeeping

#5115 Upgrade Storybook to v7.6
  webview/.storybook/main.ts
  webview/.storybook/preview.ts
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#5111 Do not pass down the grid ref
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplatePlotGroups.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/hooks/useObserveGridDimensions.ts
Labels: 🏠 housekeeping

#5105 Fix Toast messages showing a successful message after failed remote command
  extension/src/cli/dvc/config.test.ts
  extension/src/cli/dvc/config.ts
  extension/src/setup/commands/index.ts
  extension/src/test/suite/setup/index.test.ts
Labels: bug

#5125 Remove Studio data request failed Toast
  extension/src/experiments/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
Labels: bug

#5126 Fix "Add Plot" breaking dvc.yaml when there is no list indentation
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: bug

#5142 Rename "Studio" to "DVC Studio" in text instances
  README.md
  extension/resources/walkthrough/images/setup-view.png
  extension/resources/walkthrough/more-resources.md
  extension/resources/walkthrough/setup.md
  extension/src/experiments/commands/index.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/CopyStudioLink.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/shared/components/sectionContainer/SectionDescription.tsx
Labels: product
