Repository iterative/vscode-dvc, pull requests merged in 2023-09, with the labels that each got.

#4610 Stop explicitly watching temp queued experiment directories (already covered)
  extension/src/cli/dvc/constants.ts
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
Labels: 🏠 housekeeping

#4615 Send full sha for copy sha command
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: bug

#4617 Do not allow user to copy non-existent sha
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: bug

#4600 Provide shareable links for all experiments found on Studio
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/studio.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/messages.ts
  webview/src/stories/Table.stories.tsx
Labels: product

#4609 Revert collecting remote exp refs
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
Labels: 🏠 housekeeping

#4619 Patch Studio API update timinig issue
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/studio.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
Labels: product

#4607 Fix plots paths breaking on windows
  extension/src/fileSystem/util.ts
  extension/src/plots/index.ts
  extension/src/plots/util.test.ts
  extension/src/plots/util.ts
Labels: bug

#4626 Fix custom plots breaking with non-numeric values
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.test.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/quickPick.test.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/workspace.test.ts
  webview/src/plots/components/App.test.tsx
Labels: bug

#4629 Add ability to zoom and pan plots when zoomed
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  webview/src/plots/components/ZoomedInPlot.tsx
Labels: product

#4630 Add Hydra syntax hint (prompt) to input box for modify and queue experiment command
  extension/src/experiments/index.ts
  extension/src/experiments/model/modify/quickPick.test.ts
  extension/src/experiments/model/modify/quickPick.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/vscode/inputBox.ts
Labels: product

#4647 Apply selected experiment colors to custom plots
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/index.test.ts
Labels: product

#4628 Correctly parse dvc.yaml on plot creation
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: bug

#4627 Add data file validation to plots wizard
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
Labels: bug

#4586 Add top-level plots wizard
  extension/package.json
  extension/src/cli/dvc/contract.ts
  extension/src/commands/external.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
  extension/src/pipeline/register.ts
  extension/src/pipeline/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/vscode/resourcePicker.test.ts
  extension/src/vscode/resourcePicker.ts
  extension/src/vscode/title.ts
  yarn.lock
Labels: product

#4658 Fix typo in plot wizard error toast
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
Labels: bug

#4659 Fix Code Climate badges
  README.md
Labels: 🏠 housekeeping

#4657 Apply table filters to custom plot data
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
Labels: product

#4664 Add "Add Top-level Plot" command to plots webview
  extension/src/pipeline/register.ts
  extension/src/pipeline/workspace.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/emptyState/AddPlots.tsx
  webview/src/plots/components/emptyState/Welcome.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/util/messages.ts
Labels: product

#4669 Use insiders for e2e tests (chromium) missing
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#4673 Fix Vega plots disappearing
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
Labels: bug

#4677 Increase windows tests timeout
  .github/workflows/cross-platform-test.yml
Labels: 🏠 housekeeping

#4678 Remove mutli source plots encoding cache
  extension/src/plots/model/index.ts
  extension/src/plots/multiSource/collect.ts
Labels: bug

#4684 Fix type error in integration tests
  extension/src/test/suite/plots/index.test.ts
Labels: bug

#4687 Simplify data structure used to collect multisource encoding update
  extension/src/plots/multiSource/collect.ts
Labels: 🏠 housekeeping

#4680 Merge create plot commands
  extension/package.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/register.ts
  extension/src/pipeline/workspace.ts
  extension/src/plots/commands/register.ts
  extension/src/plots/index.ts
  extension/src/plots/quickPick.test.ts
  extension/src/plots/quickPick.ts
  extension/src/plots/webview/messages.ts
  extension/src/plots/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/e2e/util.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/workspace.test.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/emptyState/AddPlots.tsx
  webview/src/plots/components/emptyState/GetStarted.tsx
  webview/src/plots/components/emptyState/Welcome.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/util/messages.ts
Labels: product

#4694 Add action buttons to empty plot sections
  extension/src/plots/index.ts
  extension/src/plots/model/custom.test.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/NoPlotsAdded.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/emptyState/ErrorState.tsx
  webview/src/plots/components/templatePlots/NoPlotsToDisplay.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/util/messages.ts
Labels: product

#4722 Fix broken "With Multiple Branches" table storybook
  webview/src/stories/Table.stories.tsx
Labels: bug

#4691 Add "Parents" Columns
  extension/src/experiments/columns/collect/order.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/model.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/suite/experiments/columns/tree.test.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/body/columns/Columns.tsx
  webview/src/experiments/components/table/content/BranchCellContent.tsx
  webview/src/experiments/components/table/content/CommitCellContent.tsx
  webview/src/experiments/components/table/content/SortedTableHeader.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/util.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/columns.ts
Labels: product

#4724 Fix experiments table move to start functionality
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
Labels: bug

#4729 Ensure custom plots legend matches plot values
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
Labels: bug
