Repository iterative/vscode-dvc, pull requests merged in 2023-06, with the labels that each got.

#4024 Fix "show toast on new install" logic
  extension/src/extension.ts
  extension/src/persistence/constants.ts
  extension/src/persistence/register.ts
  extension/src/persistence/util.test.ts
  extension/src/persistence/util.ts
  extension/src/setup/util.test.ts
  extension/src/setup/util.ts
Labels: bug

#4028 Fix pushing multiple experiments
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
Labels: bug

#4037 Add default value for branch name when creating from experiment
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
Labels: product

#3980 Add a mapping from revision to branches while using only one exp show call
  extension/src/cli/git/reader.ts
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/expShow/base/gitLog.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rowOrder.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/columns/tree.test.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/plots/workspace.test.ts
  webview/__mocks__/@vscode/webview-ui-toolkit/react.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/util/strings.ts
Labels: product

#4036 Move git call into experiments data
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
Labels: 🏠 housekeeping

#4041 Fix table stories and data types
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/dataTypes/output.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/deeplyNested/output.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/survival/output.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
  extension/src/test/fixtures/expShow/uncommittedDeps/output.ts
  extension/src/test/util/experiments.ts
  webview/src/stories/Table.stories.tsx
  webview/src/stories/util.ts
Labels: bug

#4042 Do not drop experiment selection when an experiment is running and exp show errors
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
Labels: bug

#4040 Move "new to DVC" text from setup to welcome view
  extension/package.json
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/DvcUnitialized.tsx
Labels: product

#4044 Exclude codicons.mjs from eslint
  webview/.eslintrc.js
Labels: 🏠 housekeeping

#4049 Remove max version of CLI (3.0 release)
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/version.ts
  extension/src/setup/runner.test.ts
Labels: 🏠 housekeeping

#4052 Remove mention of public beta from the README
  README.md
Labels: 🏠 housekeeping

#4055 Rearrange DVCLive examples in setup screen
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/experiments/styles.module.scss
Labels: 🏠 housekeeping

#4063 Use shields.io for marketplace badges in README
  README.md
Labels: 🏠 housekeeping

#4070 Fix failing tests
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#4068 fix(plots): correct the empty screen link to the dvc docs
  webview/src/plots/components/GetStarted.tsx
Labels: bug, A: plots

#4045 Add PYTHONPATH to environment variables if the Python extension makes it available
  .vscode/settings.json
  README.md
  extension/src/cli/dvc/config.test.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/dvc/options.test.ts
  extension/src/cli/dvc/options.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/dvc/runner.ts
  extension/src/cli/dvc/viewer.ts
  extension/src/config.ts
  extension/src/extensions/python.ts
  extension/src/setup/index.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
  extension/src/test/suite/cli/dvc/viewer.test.ts
  extension/src/test/suite/config.test.ts
  extension/src/test/suite/status.test.ts
Labels: product

#4073 Update useful commands reference in the README
  README.md
Labels: 🏠 housekeeping

#4076 Fix scheduled CLI output test (correctly mock config)
  extension/src/test/cli/util.ts
Labels: 🏠 housekeeping

#4062 Show CLI errors generated by exp show
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/util/jest/index.ts
  extension/src/tree/index.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/ErrorState.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/messages.ts
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/errorIcon/ErrorIcon.tsx
  webview/src/shared/components/errorIcon/styles.module.scss
  webview/src/stories/Table.stories.tsx
Labels: product

#4075 Refactor empty state code for experiments and plots
  webview/src/experiments/components/ErrorState.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/GetStarted.tsx
  webview/src/experiments/components/emptyState/AddColumns.tsx
  webview/src/experiments/components/emptyState/ErrorState.tsx
  webview/src/experiments/components/emptyState/GetStarted.tsx
  webview/src/experiments/components/emptyState/Welcome.tsx
  webview/src/experiments/util/messages.ts
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/emptyState/AddPlots.tsx
  webview/src/plots/components/emptyState/EmptyState.tsx
  webview/src/plots/components/emptyState/ErrorState.tsx
  webview/src/plots/components/emptyState/GetStarted.tsx
  webview/src/plots/components/emptyState/Welcome.tsx
  webview/src/plots/components/emptyState/styles.module.scss
  webview/src/plots/components/messages.ts
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/getStarted/GetStarted.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#4077 Standardize use of send message across setup, experiments and plots
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/util/messages.ts
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/emptyState/AddPlots.tsx
  webview/src/plots/components/emptyState/ErrorState.tsx
  webview/src/plots/components/emptyState/Welcome.tsx
  webview/src/plots/components/messages.ts
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/util/messages.ts
  webview/src/setup/components/App.tsx
  webview/src/setup/components/GetStarted.tsx
  webview/src/setup/components/dvc/CliIncompatible.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/DvcEnvCommandRow.tsx
  webview/src/setup/components/dvc/DvcUnitialized.tsx
  webview/src/setup/components/dvc/GitUnitialized.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/experiments/NeedsGitCommit.tsx
  webview/src/setup/components/remotes/Connect.tsx
  webview/src/setup/components/remotes/RemoteDetails.tsx
  webview/src/setup/components/studio/Connect.tsx
  webview/src/setup/components/studio/Settings.tsx
  webview/src/setup/util/messages.ts
Labels: 🏠 housekeeping

#4085 Show information toast when trying to exceed max number of plotted experiments
  README.md
  extension/package.json
  extension/src/experiments/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/config.ts
Labels: product

#4086 Improve README
  README.md
  extension/resources/walkthrough/more-resources.md
Labels: 🏠 housekeeping

#4092 Correctly handle string arrays in modify and commands
  extension/src/experiments/model/modify/collect.test.ts
  extension/src/experiments/model/modify/collect.ts
  extension/src/experiments/model/modify/quickPick.test.ts
  extension/src/experiments/model/modify/quickPick.ts
Labels: bug

#4099 Fix broken experiments table column shadow
  webview/src/experiments/components/table/body/branchDivider/BranchDivider.tsx
Labels: bug

#4095 Only use selected params for modify and commands
  extension/src/experiments/model/modify/quickPick.test.ts
  extension/src/experiments/model/modify/quickPick.ts
Labels: 🏠 housekeeping

#4102 Fix custom plot tooltips
  extension/src/plots/model/custom.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
Labels: bug

#4104 Remove garbage collect experiments command
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/quickPick.test.ts
  extension/src/experiments/quickPick.ts
  extension/src/test/e2e/util.ts
Labels: 🏠 housekeeping

#4106 Fix e2e tests
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/util.ts
Labels: 🏠 housekeeping

#4091 Add `--user` flag to global dvc auto installation
  extension/src/extensions/python.test.ts
  extension/src/extensions/python.ts
  extension/src/setup/autoInstall.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/autoInstall.test.ts
  extension/src/test/suite/setup/index.test.ts
Labels: bug

#4098 Update Setup "dvc is unavailable" section text content
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/test/suite/setup/index.test.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/DvcEnvCommandRow.tsx
  webview/src/setup/components/dvc/styles.module.scss
  webview/src/setup/state/dvcSlice.ts
  webview/src/stories/Setup.stories.tsx
Labels: product

#4117 Fix never ending loading on no experiments data
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/test/cli/expShow.test.ts
  extension/src/test/suite/plots/index.test.ts
Labels: bug

#4116 Revert string quoting behaviour in modify and commands
  extension/src/experiments/model/modify/collect.test.ts
  extension/src/experiments/model/modify/collect.ts
  extension/src/experiments/model/modify/quickPick.test.ts
  extension/src/experiments/model/modify/quickPick.ts
Labels: bug

#4118 Fix "Get Started" walkthrough typos and outdated mentions
  extension/package.json
  extension/resources/walkthrough/command-palette.md
  extension/resources/walkthrough/experiments-table.md
  extension/resources/walkthrough/live-plots.md
  extension/resources/walkthrough/more-resources.md
  extension/resources/walkthrough/plots.md
  extension/resources/walkthrough/run-experiments.md
  extension/resources/walkthrough/view-container.md
Labels: 🏠 housekeeping

#4121 Switch experiment table radio buttons to plot icons
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/shared/components/Icon.tsx
  webview/src/shared/variables.scss
Labels: product

#4126 Update README with up to date information
  README.md
Labels: 🏠 housekeeping

#4137 Use regex to handle detached HEAD branch name in other languages
  extension/src/util/stdout.test.ts
  extension/src/util/stdout.ts
Labels: bug

#4124 Point users to Python extension in DVC Setup
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/styles.module.scss
  webview/src/setup/components/remotes/ShowExtension.tsx
  webview/src/setup/components/shared/ExtensionLink.tsx
  webview/src/shared/components/button/Button.tsx
Labels: product

#4147 Fix plots ribbon copy buttons
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
Labels: bug

#4133 Update the logic to identify a failed process
  extension/src/cli/index.ts
  extension/src/cli/util.ts
  extension/src/vscode/outputChannel.ts
Labels: bug

#4135 Adjust plot ribbon tooltips
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/util.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/workspace.test.ts
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/variables.scss
Labels: product

#4148 Remove Setup's "Get Started" Section
  extension/src/setup/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/GetStarted.tsx
  webview/src/setup/components/dvc/Dvc.tsx
  webview/src/setup/components/shared/util.ts
  webview/src/shared/components/sectionContainer/SectionDescription.tsx
  webview/src/stories/Setup.stories.tsx
Labels: product

#4150 Support more languages (git branch)
  extension/src/cli/git/executor.ts
  extension/src/cli/git/index.ts
  extension/src/cli/git/options.ts
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/util/stdout.test.ts
  extension/src/util/stdout.ts
Labels: 🏠 housekeeping

#4154 Add "Setup" section to "Get Started" walkthrough
  extension/package.json
  extension/resources/walkthrough/command-palette.md
  extension/resources/walkthrough/images/setup-view.png
  extension/resources/walkthrough/setup.md
Labels: product

#4163 Further reduce the number of calls to Git
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/util.ts
Labels: 🏠 housekeeping

#4159 Rename `firstThreeColumns`
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/model/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/util/jest/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
Labels: 🏠 housekeeping

#4155 Use first three metrics and params in table tooltips & quick picks
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/columns/util.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/model/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/util/jest/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
Labels: product

#4166 Bypass process manager debounce in refresh plot revisions tests
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
Labels: 🏠 housekeeping

#4165 Handle Git not being installed (Setup)
  extension/src/cli/git/constants.ts
  extension/src/cli/git/executor.ts
  extension/src/cli/git/index.ts
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/setup/index.ts
  extension/src/test/suite/fileSystem/index.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  webview/src/setup/components/dvc/GitUnitialized.tsx
Labels: bug

#4179 Fix table webview stuck on error page
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
Labels: bug

#4162 Add CSS selector & variable naming rules
  webview/.stylelintrc.js
  webview/src/experiments/components/table/styles.module.scss
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/constants.ts
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/iconMenu/styles.module.scss
  webview/src/shared/components/modal/styles.module.scss
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/components/tooltip/styles.module.scss
  webview/src/shared/mixins.scss
  webview/src/shared/styles.scss
  webview/src/shared/variables.scss
Labels: 🏠 housekeeping

#4195 Fix unresolved promises in local e2e tests
  extension/src/test/e2e/util.ts
Labels: bug
