Repository iterative/vscode-dvc, pull requests merged in 2023-03, with the labels that each got.

#3365 Watch for dvc.yaml changes for manually added stages
  extension/src/experiments/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/shared/components/button/Button.tsx
  webview/src/shared/components/button/IconButton.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3368 Do not go into pipeline stage creation mode if dvc.yaml is invalid
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
Labels: product

#3376 Rename size to nbItemsPerRow
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/util.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#3377 Rename plot sizes pt. 2
  extension/src/persistence/constants.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/util.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#3390 Remove package.nls
  extension/package.json
  extension/package.nls.json
Labels: bug

#3387 Add live share experiment to Studio
  README.md
  extension/package.json
  extension/src/cli/dvc/runner.ts
  extension/src/connect/index.ts
  extension/src/experiments/commands/index.ts
  extension/src/extension.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
  extension/src/test/suite/connect/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/vscode/config.ts
Labels: product

#3379 Add Studio settings page
  extension/package.json
  extension/src/connect/index.ts
  extension/src/connect/webview/contract.ts
  extension/src/test/suite/connect/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/webview/contract.ts
  webview/src/connect/components/App.test.tsx
  webview/src/connect/components/App.tsx
  webview/src/connect/components/Studio.tsx
  webview/src/connect/components/messages.ts
  webview/src/stories/Connect.stories.tsx
Labels: product

#3382 Fix plots "get started" walkthrough
  extension/src/plots/model/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
Labels: bug

#3398 Have queue workers respect dvc.studio.shareExperimentsLive
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/dvc/options.ts
  extension/src/cli/dvc/runner.ts
  extension/src/extension.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/util.ts
Labels: product

#3395 Remove vega-functions & vega-scale resolutions
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#3400 Switch add Studio access token to update when Studio is connected
  extension/package.json
  extension/src/commands/external.ts
  extension/src/connect/register.ts
  extension/src/telemetry/constants.ts
  webview/src/connect/components/App.test.tsx
  webview/src/connect/components/Studio.tsx
Labels: product

#3403 Added a story to visualize the icons
  webview/src/stories/Icons.stories.tsx
  webview/src/stories/components/IconWrapper.tsx
  webview/src/stories/components/IconsWrapper.tsx
  webview/src/stories/components/styles.module.scss
Labels: 🏠 housekeeping

#3416 Pin and upgrade webview dependencies
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3423 Remove unnecessary Vega dependency
  extension/package.json
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  webview/package.json
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/constants.ts
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  yarn.lock
Labels: 🏠 housekeeping

#3424 Pin @tanstack/react-table
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3405 Select the number of items per row from slider
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/Resizer.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/util.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/shared/components/slider/MinMaxSlider.tsx
  webview/src/shared/components/slider/styles.module.scss
  webview/src/shared/components/virtualizedGrid/VirtualizedGrid.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/Slider.stories.tsx
  webview/src/test/mouseEventsWithCoordinates.ts
Labels: product

#3422 Send single event to share experiment to Studio
  extension/src/patch.ts
  extension/src/test/suite/patch.test.ts
Labels: 🏠 housekeeping

#3426 Fix typo
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/vega/util.test.ts
  extension/src/plots/vega/util.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/shared/components/virtualizedGrid/VirtualizedGrid.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#3432 Hide Studio view during onboarding process/startup
  extension/package.json
Labels: bug

#3433 Add zoom plot telemetry event
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/messages.ts
Labels: 🏠 housekeeping

#3431 Move filter by and sort by views to the bottom and collapse for new users
  extension/package.json
Labels: product

#3421 Add command to reset state
  extension/package.json
  extension/src/commands/external.ts
  extension/src/extension.ts
  extension/src/persistence/register.ts
  extension/src/persistence/util.test.ts
  extension/src/persistence/util.ts
  extension/src/telemetry/constants.ts
  extension/src/test/util/index.ts
Labels: product

#3435 Clean up setup internals
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/git/executor.ts
  extension/src/cli/git/reader.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/setup/register.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3444 Revert smooth slider background color
  webview/src/plots/components/styles.module.scss
Labels: product

#3440 Create (shared) section container component
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
Labels: 🏠 housekeeping

#3443 Make the plot sizing sliders sticky
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/styles.module.scss
Labels: product

#3460 Clean up column path logic in custom state
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
Labels: 🏠 housekeeping

#3464 Make className optional in SectionContainer
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
Labels: bug

#3461 Fix flaky integration tests
  extension/src/test/suite/extension.test.ts
Labels: 🏠 housekeeping

#3462 Provide option to open and focus relevant Setup section through UI
  extension/package.json
  extension/resources/walkthrough/install-dvc.md
  extension/resources/walkthrough/setup-project.md
  extension/src/cli/dvc/discovery.ts
  extension/src/commands/external.ts
  extension/src/commands/util.ts
  extension/src/experiments/index.ts
  extension/src/interfaces.ts
  extension/src/plots/index.ts
  extension/src/setup/collect.ts
  extension/src/setup/index.ts
  extension/src/setup/register.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/webview/repository.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
Labels: product

#3463 Add show experiments button to final experiments screen
  extension/src/setup/index.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/Experiments.tsx
  webview/src/setup/components/messages.ts
  webview/src/shared/components/Icon.tsx
  webview/src/shared/components/icons/Beaker.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#3465 Make section headers sticky
  extension/src/plots/webview/contract.ts
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/iconMenu/IconMenuItem.tsx
  webview/src/shared/components/iconMenu/styles.module.scss
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/components/slider/ItemsSlider.tsx
  webview/src/shared/components/slider/MinMaxSlider.tsx
  webview/src/shared/components/slider/Slider.tsx
  webview/src/stories/Slider.stories.tsx
Labels: product

#3474 Add show setup commands
  extension/package.json
  extension/src/commands/external.ts
  extension/src/setup/register.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/index.test.ts
Labels: product

#3469 Consolidate and fix Setup stories
  webview/src/stories/CliIncompatible.stories.tsx
  webview/src/stories/CliUnavailable.stories.tsx
  webview/src/stories/NeedsGitCommit.stories.tsx
  webview/src/stories/NoData.stories.tsx
  webview/src/stories/ProjectUninitialized.stories.tsx
  webview/src/stories/Setup.stories.tsx
Labels: 🏠 housekeeping

#3471 Add react/js-curly-brace-presense eslint rule
  .eslintrc.js
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Errors.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/Studio.tsx
  webview/src/shared/components/button/RefreshButton.tsx
  webview/src/shared/components/contextMenu/ContextMenu.tsx
Labels: 🏠 housekeeping

#3481 Move e2e tests to insiders
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#3467 Open comparison table images when clicking on them
  extension/src/fileSystem/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/messages.ts
Labels: product

#3480 Resize comparison table with slider
  extension/src/persistence/constants.ts
  extension/src/persistence/util.test.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/util/styles.ts
Labels: product

#3499 Add experiment_rev into payload for share experiment to Studio
  extension/src/patch.ts
  extension/src/test/suite/patch.test.ts
Labels: bug

#3466 Consolidate `collectCustomPlots`
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
Labels: 🏠 housekeeping

#3489 Make plots vertical scrollbars local to sections
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
Labels: product

#3508 Create multiple Redux actions for the table data
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/tableDataSlice.ts
Labels: 🏠 housekeeping

#3513 Increase coverage
  webview/jest.config.js
  webview/setup-tests.js
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/shared/components/selectMenu/SingleSelect.tsx
  webview/src/util/array.test.ts
  webview/src/util/ids.test.ts
  webview/src/util/styles.test.ts
Labels: 🏠 housekeeping

#3515 Drop overall test coverage requirement (unblock)
  package.json
Labels: 🏠 housekeeping

#3404 Move trends plots inside of "Custom" section
  extension/resources/walkthrough/images/plots-custom.png
  extension/resources/walkthrough/images/plots-trends.png
  extension/resources/walkthrough/live-plots.md
  extension/resources/walkthrough/plots.md
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.test.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/model/quickPick.test.ts
  extension/src/plots/model/quickPick.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/e2e/extension.test.ts
  extension/src/test/fixtures/expShow/base/checkpointPlots.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlots.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/checkpointPlots/checkpointPlotsSlice.ts
  webview/src/plots/components/checkpointPlots/util.ts
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/customPlots/util.ts
  webview/src/plots/components/plotDataStore.ts
  webview/src/plots/hooks/useGetPlot.ts
  webview/src/plots/store.ts
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/stories/Plots.stories.tsx
Labels: product

#3503 Always call plots diff with workspace as the first revision (get correct templates)
  extension/src/plots/data/collect.ts
  extension/src/plots/data/index.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
  extension/src/util/array.test.ts
  extension/src/util/array.ts
Labels: bug

#3504 Make plots tree items decoratable
  extension/src/experiments/columns/tree.ts
  extension/src/path/selection/model.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/paths/tree.test.ts
  extension/src/plots/paths/tree.ts
  extension/src/tree/index.ts
Labels: 🏠 housekeeping

#3507 Fix the comparison table images width
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: bug

#3521 Add etc/no-assign-mutated-array rule
  .eslintrc.js
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/model/filterBy/tree.ts
  extension/src/experiments/model/sortBy/tree.ts
  extension/src/experiments/model/status/colors.ts
  extension/src/experiments/model/status/index.ts
  extension/src/experiments/model/tree.ts
  extension/src/fileSystem/index.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/data/collect.ts
  extension/src/plots/multiSource/collect.ts
  extension/src/repository/model/tree.ts
  extension/src/setup/index.ts
  extension/src/setup/quickPick.ts
  extension/src/test/e2e/extension.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/util/array.ts
  languageServer/src/textDocument.ts
  webview/src/test/tableDataFixture.ts
  webview/src/util/ids.ts
Labels: 🏠 housekeeping

#3514 Remove error for invalid dvc.yaml if no dvc.yaml file
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: bug

#3524 Add missing loading screen to Custom section
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
Labels: bug

#3518 Cleanup plots workspace state
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
Labels: 🏠 housekeeping

#3529 Update timeout for webview test
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#3533 Fix nesting of Setup test
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#3526 Filter custom plot creation options
  extension/src/plots/model/custom.test.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/quickPick.test.ts
  extension/src/plots/model/quickPick.ts
  extension/src/plots/webview/messages.ts
Labels: product

#3543 Increase CodeClimate method line count threshold to 40
  .codeclimate.json
Labels: 🏠 housekeeping

#3556 Move function complexity threshold to 6 (+1)
  .codeclimate.json
  .eslintrc.js
  extension/src/test/suite/plots/data/index.test.ts
  webview/src/experiments/components/App.tsx
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
Labels: 🏠 housekeeping

#3550 Improve Custom Plot Creation
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.test.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.ts
  extension/src/plots/model/quickPick.test.ts
  extension/src/plots/model/quickPick.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/util.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
Labels: product

#3535 Add a button to show more commits
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/ShowMoreCommitsRow.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/messages.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3562 Add button to show less commits
  extension/src/experiments/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/ShowMoreCommitsRow.tsx
  webview/src/experiments/components/table/messages.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3573 Remove vega-util truncation for ribbon tooltip
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
Labels: 🏠 housekeeping

#3587 Remove experiment checkpoints from tree
  extension/package.json
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/util/jest/index.ts
Labels: 🏠 housekeeping

#3589 Remove experiment checkpoints from select experiments to plot
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
Labels: 🏠 housekeeping

#3590 Remove experiment checkpoints from plot color collection
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#3601 Send back change in commits to show
  extension/src/experiments/webview/messages.ts
Labels: bug
