Repository iterative/vscode-dvc, pull requests merged in 2023-04, with the labels that each got.

#3591 Add experiment state indicators to commit records in table
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/experiments/util/rows.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3595 Remove references to experiment checkpoints from walkthrough
  extension/resources/walkthrough/experiments-table.md
  extension/resources/walkthrough/images/experiments-table-from-side-bar.png
  extension/resources/walkthrough/images/experiments-table.png
  extension/resources/walkthrough/images/view-container-columns.png
  extension/resources/walkthrough/images/view-container-experiments.png
  extension/resources/walkthrough/images/view-container-filter.png
  extension/resources/walkthrough/images/view-container-plots.png
  extension/resources/walkthrough/images/view-container-show.png
  extension/resources/walkthrough/images/view-container-sort.png
  extension/resources/walkthrough/images/view-container.png
  extension/resources/walkthrough/plots.md
  extension/resources/walkthrough/view-container.md
Labels: 🏠 housekeeping

#3596 Remove experiment checkpoints from table context menu
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: 🏠 housekeeping

#3520 Use plot errors to display correct messages for missing plots
  extension/src/cli/dvc/contract.ts
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/index.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/shared/components/errorTooltip/ErrorTooltip.tsx
  webview/src/shared/components/errorTooltip/styles.module.scss
  webview/src/stories/ComparisonTable.stories.tsx
Labels: bug

#3522 Show plots errors in plots tree
  extension/src/experiments/columns/tree.test.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
  extension/src/plots/errors/decorationProvider.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/index.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/paths/tree.test.ts
  extension/src/plots/paths/tree.ts
Labels: product

#3532 Refresh cached plots data on every update
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/plots/data/collect.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
  webview/src/plots/components/LoadingSection.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
Labels: bug

#3544 Ensure unfetched image plots are on disk before providing URL to webview
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/stories/ComparisonTable.stories.tsx
Labels: bug

#3545 Fix removal of existing commit errors
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
Labels: bug

#3546 Group shared ErrorTooltip with Tooltip
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/shared/components/errorTooltip/styles.module.scss
  webview/src/shared/components/tooltip/ErrorTooltip.tsx
  webview/src/shared/components/tooltip/styles.module.scss
Labels: 🏠 housekeeping

#3547 Account for data key being optional in plots diff output
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
Labels: bug

#3548 Consolidate tree view error decoration providers
  extension/src/experiments/model/decorationProvider.ts
  extension/src/plots/errors/decorationProvider.ts
  extension/src/plots/index.ts
  extension/src/repository/index.ts
  extension/src/tree/decorationProvider/error.ts
  extension/src/tree/decorationProvider/index.ts
Labels: 🏠 housekeeping

#3555 Remove code that refreshes a single plot revision (no longer possible)
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/messages.ts
  webview/src/plots/components/ribbon/Ribbon.tsx
Labels: 🏠 housekeeping

#3557 Ensure the correct fetched status is applied when overriding plot revisions
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
Labels: bug

#3569 Display error thrown by Plots Diff in Plots tree
  extension/src/experiments/columns/tree.test.ts
  extension/src/experiments/columns/tree.ts
  extension/src/experiments/model/filterBy/tree.ts
  extension/src/experiments/model/tree.ts
  extension/src/path/selection/model.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/index.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/paths/tree.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/error.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/repository/model/tree.test.ts
  extension/src/repository/model/tree.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/tree/index.ts
Labels: product

#3570 Show errors in plots ribbon
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/components/tooltip/ErrorTooltip.tsx
  webview/src/stories/Ribbon.stories.tsx
Labels: product

#3576 Ensure that data for broken revisions is dropped
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/test/suite/plots/index.test.ts
Labels: bug

#3578 Move error formatting logic out to clients
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/stories/ComparisonTable.stories.tsx
Labels: 🏠 housekeeping

#3558 Fix scheduled CLI output test by updating expected demo project output (plots diff breaking change)
  extension/src/test/cli/plotsDiff.test.ts
Labels: bug

#3575 Move custom plot spec creation to backend
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/suite/plots/util.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/util.ts
  webview/src/stories/Plots.stories.tsx
Labels: 🏠 housekeeping

#3613 Move e2e tests to stable
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#3523 Show "Custom" section in "Get Started" screen
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/ribbonSlice.ts
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/getStarted/GetStarted.tsx
Labels: product

#3608 Show revision level plot errors
  extension/src/cli/dvc/contract.ts
  extension/src/plots/errors/collect.test.ts
  extension/src/plots/errors/collect.ts
  extension/src/plots/errors/model.ts
  extension/src/plots/index.ts
  extension/src/plots/paths/collect.ts
  extension/src/test/suite/plots/index.test.ts
Labels: product

#3627 Add cli error indicator into plots webview
  extension/src/plots/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/ErrorIcon.tsx
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/webviewSlice.ts
  webview/src/stories/Plots.stories.tsx
Labels: product

#3632 Update webdriverio-monorepo and fix e2e tests
  extension/package.json
  extension/src/test/e2e/extension.test.ts
  yarn.lock
Labels: 🏠 housekeeping

#3614 Add a branches view to the experiments table
  extension/src/cli/dvc/constants.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/ShowMoreCommitsRow.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/messages.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3635 Add a space after the checkbox action in the table
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#3624 Remove checkpoints from plots
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/fixtures/plotsDiff/util.ts
  extension/src/test/fixtures/plotsDiff/vega.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
Labels: 🏠 housekeeping

#3629 Add custom plot commands to the command pallete
  extension/package.json
  extension/src/commands/external.ts
  extension/src/plots/commands/register.ts
  extension/src/plots/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/plots/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/workspace.test.ts
Labels: product

#3634 Update custom plot spec
  extension/src/plots/model/custom.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  webview/src/plots/components/App.test.tsx
Labels: product

#3642 Make sure changing the number of revisions will trigger an update for the scale of the multiview plot
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
Labels: bug

#3639 Remove checkpoints from experiment collection
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/model/accumulator.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/plots/model/index.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/modified/output.ts
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/stories/util.ts
Labels: 🏠 housekeeping

#3641 Show duplicate revisions when experiment finishes running in the workspace
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: bug

#3650 Add 20px to min width of experiments column
  webview/src/experiments/components/Experiments.tsx
Labels: 🏠 housekeeping

#3646 Add custom plot to e2e test
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/util.ts
Labels: 🏠 housekeeping

#3655 Add Setup DVC Section
  extension/package.json
  extension/resources/walkthrough/install-dvc.md
  extension/src/commands/external.ts
  extension/src/commands/util.ts
  extension/src/setup/register.ts
  extension/src/setup/webview/contract.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/Dvc.tsx
  webview/src/setup/components/Experiments.tsx
  webview/src/setup/components/Studio.tsx
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/stories/Setup.stories.tsx
Labels: product

#3669 Fix broken collapsed section info tooltips
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
Labels: bug

#3678 fix(table): DnD landing zone covers the whole cell in the table
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug, A: table

#3683 fix(table): DnD behavior for groups
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/util/columns.ts
Labels: bug, A: table

#3686 Do not convert the manually entered path into a relative path
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: bug

#3670 Hidden: Add and remove branches to the experiments table
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/watcher.ts
  extension/src/persistence/constants.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/util.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/commitsAndBranches/AddAndRemoveBranches.tsx
  webview/src/experiments/components/table/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/messages.ts
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
  webview/src/util/flags.ts
Labels: product

#3684 Remove checkpoints model and file system watcher
  extension/src/data/index.ts
  extension/src/experiments/checkpoints/collect.test.ts
  extension/src/experiments/checkpoints/collect.ts
  extension/src/experiments/checkpoints/model.test.ts
  extension/src/experiments/checkpoints/model.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/fileSystem/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3707 Avoid CSS element selection in table styles
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: 🏠 housekeeping

#3681 Group table body styles
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: 🏠 housekeeping

#3674 Clean up table head styles
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/experiments/components/table/content/Header.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: 🏠 housekeeping

#3696 Stop importing CSS into storybook files
  webview/.storybook/preview.ts
  webview/.storybook/styles.scss
  webview/.storybook/test-vscode-styles.scss
  webview/src/stories/ContextMenu.stories.tsx
  webview/src/stories/IconMenu.stories.tsx
  webview/src/stories/Icons.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/Ribbon.stories.tsx
  webview/src/stories/Setup.stories.tsx
  webview/src/stories/Slider.stories.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/stories/Tooltip.stories.tsx
Labels: 🏠 housekeeping

#3716 Clean up shared styles
  webview/.storybook/preview.ts
  webview/.storybook/styles.scss
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/index.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/index.tsx
  webview/src/setup/index.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/mixins.scss
  webview/src/shared/styles.scss
Labels: 🏠 housekeeping

#3667 Group table styles
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/experiments/components/table/content/Header.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: 🏠 housekeeping

#3713 Extend timeout of run experiment test (e2e)
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/util.ts
Labels: bug

#3712 Prevent plotting of running experiments
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/workspace.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
Labels: bug

#3715 Trigger plot updates whenever commit data changes
  extension/src/plots/index.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/util/object.test.ts
  extension/src/util/object.ts
Labels: bug

#3706 Clean up table file structure
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/CellHintTooltip.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
  webview/src/experiments/components/table/body/CellSecondaryName.tsx
  webview/src/experiments/components/table/body/ExperimentGroup.tsx
  webview/src/experiments/components/table/body/NestedRow.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/WorkspaceRowGroup.tsx
  webview/src/experiments/components/table/commitsAndBranches/AddAndRemoveBranches.tsx
  webview/src/experiments/components/table/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/state/headerDropTargetSlice.ts
  webview/src/experiments/state/headersSlice.ts
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/store.ts
  webview/src/experiments/util/interfaces.ts
  webview/src/experiments/util/messages.ts
  webview/src/stories/Table.stories.tsx
Labels: 🏠 housekeeping

#3729 Fix broken experiments table column shadow
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#3724 Fix experiment id for commits (shown in plots)
  extension/src/experiments/model/collect.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
Labels: bug

#3728 Fix warnings produced by integration tests
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/vscode/walkthrough.test.ts
Labels: 🏠 housekeeping

#3727 Set scm running context to false if command fails
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
Labels: bug

#3726 Force commit action by default
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/repository/commands/index.ts
  extension/src/repository/commands/register.ts
  extension/src/test/suite/repository/sourceControlManagement/index.test.ts
Labels: bug

#3725 Standardize how experiment information is displayed in plots ribbon
  extension/src/experiments/model/collect.ts
  extension/src/experiments/webview/contract.ts
  extension/src/plots/model/index.test.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/stories/Ribbon.stories.tsx
Labels: product

#3737 Fix e2e tests failing
  extension/src/test/e2e/extension.test.ts
Labels: 🏠 housekeeping

#3734 Fix scheduled CLI output test (workspace has no timestamp)
  extension/src/test/cli/expShow.test.ts
Labels: bug

#3735 Add multiple branches support inside the experiments table
  extension/src/experiments/webview/contract.ts
  extension/src/test/e2e/extension.test.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/body/PreviousCommitsRow.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/WorkspaceRowGroup.tsx
  webview/src/experiments/components/table/body/branchDivider/BranchDivider.tsx
  webview/src/experiments/components/table/body/branchDivider/styles.module.scss
  webview/src/experiments/components/table/body/commitsAndBranches/AddAndRemoveBranches.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/styles.module.scss
  webview/src/experiments/components/table/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/shared/components/icons/GitMerge.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/stories/Icons.stories.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/stories/util.ts
  webview/src/test/experimentsTable.tsx
  webview/src/test/sort.ts
Labels: product

#3736 Add Stylelint
  .vscode/settings.json
  package.json
  turbo.json
  webview/.stylelintrc.js
  webview/package.json
  webview/src/experiments/components/table/body/branchDivider/styles.module.scss
  webview/src/experiments/components/table/body/commitsAndBranches/styles.module.scss
  webview/src/experiments/components/table/styles.module.scss
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/plots/components/styles.module.scss
  webview/src/shared/components/codeSlider/styles.module.scss
  webview/src/shared/components/copyButton/styles.module.scss
  webview/src/shared/components/emptyState/styles.module.scss
  webview/src/shared/components/iconMenu/styles.module.scss
  webview/src/shared/components/messagesMenu/styles.module.scss
  webview/src/shared/components/modal/styles.module.scss
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/components/selectMenu/styles.module.scss
  webview/src/shared/components/slider/styles.module.scss
  webview/src/shared/components/tooltip/styles.module.scss
  webview/src/shared/styles.scss
  webview/src/shared/variables.scss
  webview/src/stories/components/styles.module.scss
  yarn.lock
Labels: 🏠 housekeeping

#3744 Upgrade Storybook to v7
  webview/.storybook/main.ts
  webview/.storybook/preview.ts
  webview/package.json
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/ComparisonTableHeader.stories.tsx
  webview/src/stories/ContextMenu.stories.tsx
  webview/src/stories/IconMenu.stories.tsx
  webview/src/stories/Icons.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/Ribbon.stories.tsx
  webview/src/stories/Setup.stories.tsx
  webview/src/stories/Slider.stories.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/stories/Tooltip.stories.tsx
  yarn.lock
Labels: 🏠 housekeeping

#3765 Make the table more compact with branches and actions
  extension/src/test/e2e/extension.test.ts
  webview/src/experiments/components/table/body/PreviousCommitsRow.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/branchDivider/BranchDivider.tsx
  webview/src/experiments/components/table/body/branchDivider/styles.module.scss
  webview/src/experiments/components/table/body/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/styles.module.scss
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/Table.stories.tsx
Labels: product

#3769 Watch all workspace folders for changes in dot folders
  extension/src/setup/index.ts
Labels: bug

#3770 Switch executeDvcProcess method to protected
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/index.ts
Labels: 🏠 housekeeping

#3780 Ensure duplicate colors are not made available during collection
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
Labels: bug

#3768 Use dvc config to store and access studio.token
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/dvc/reader.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/telemetry/uuid.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/util/appdirs.test.ts
  extension/src/util/appdirs.ts
Labels: product

#3701 Use exp push to share experiments to Studio
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/external.ts
  extension/src/commands/internal.ts
  extension/src/experiments/commands/index.ts
  extension/src/extension.ts
  extension/src/patch.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/patch.test.ts
  extension/src/vscode/toast.ts
Labels: 🏠 housekeeping

#3771 Remove commit and share and share as branch options
  extension/package.json
  extension/src/cli/git/constants.ts
  extension/src/cli/git/executor.test.ts
  extension/src/cli/git/executor.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: 🏠 housekeeping

#3777 Stub dvc config calls in integration tests
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/util.ts
Labels: 🏠 housekeeping

#3778 Rename exp commands to closer match CLI
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: 🏠 housekeeping

#3779 Add GIT_TERMINAL_PROMPT=0 to DVC environment variables
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/options.test.ts
  extension/src/cli/dvc/options.ts
  extension/src/cli/dvc/reader.test.ts
Labels: bug

#3774 Fix available revisions for multi view plots
  extension/src/plots/model/collect.ts
Labels: bug
