Repository iterative/vscode-dvc, pull requests merged in 2023-01, with the labels that each got.

#3029 Update experiment secondary name
  extension/src/experiments/model/collect.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/Table.stories.tsx
  webview/src/stories/util.ts
Labels: product

#3030 Enable sub-project selection in monorepos
  README.md
  extension/package.json
  extension/package.nls.json
  extension/src/config.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/setup/index.ts
  extension/src/test/suite/config.test.ts
  extension/src/vscode/config.ts
Labels: product

#3034 Use cml to create release PR
  .github/workflows/create-release-pr.yml
  .github/workflows/publish.yml
Labels: 🏠 housekeeping

#3035 Restructure experiment commit message logic
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/extension.test.ts
Labels: 🏠 housekeeping

#3016 Add commit messages to experiment views
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/extension.test.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/Table.stories.tsx
  webview/src/stories/util.ts
Labels: product

#3039 Reinstate @typescript-eslint/no-unused-vars as error
  .eslintrc.js
  extension/src/config.ts
Labels: 🏠 housekeeping

#3040 Add project selection quick pick
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/config.ts
  extension/src/setup/index.ts
  extension/src/setup/quickPick.test.ts
  extension/src/setup/quickPick.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/vscode/title.ts
Labels: product

#3027 Fix stop button
  extension/package.json
  extension/src/context.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/fileSystem/index.ts
  extension/src/processExecution.ts
  extension/src/test/suite/context.test.ts
Labels: bug

#3041 Add context key enum
  extension/package.json
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/context.ts
  extension/src/experiments/context.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/workspace.ts
  extension/src/setup/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/context.test.ts
  extension/src/vscode/context.ts
  extension/src/webview/constants.ts
  extension/src/webview/index.ts
Labels: 🏠 housekeeping

#3046 Suppress integration test warninngs
  extension/src/test/suite/config.test.ts
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#3045 Use process polling to ensure DVCLive only PIDs are still running
  extension/src/experiments/index.ts
  extension/src/fileSystem/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/util.ts
Labels: bug

#3048 Enable the user to specify a number of concurrent jobs when starting the experiments queue
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/cli/dvc/runner.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/util/number.ts
  extension/src/vscode/inputBox.ts
  extension/src/vscode/title.ts
Labels: product

#3049 Consolidate use of input box validation
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/webview/messages.ts
  extension/src/vscode/inputBox.ts
Labels: 🏠 housekeeping

#3052 Stub getLastThreeCommitMessages in integration tests
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3053 Fix missing commit messages in experiment branches
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/util.ts
Labels: bug

#3056 Fix filtering and add missing experiments on quick pick experiment selection
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPicks.ts
  extension/src/experiments/quickPick.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/quickPick.ts
Labels: bug

#3054 Add new stop queue action
  extension/package.json
  extension/package.nls.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#3071 Actions - fix newlines in PR
  .github/workflows/create-release-pr.yml
Labels: 🏠 housekeeping

#3067 Add first three columns to all experiment quick pick selection
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPicks.ts
  extension/src/experiments/model/util.ts
  extension/src/experiments/quickPick.test.ts
  extension/src/experiments/quickPick.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#3070 Fix flaky setup tests
  extension/src/config.ts
  extension/src/setup/index.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
Labels: 🏠 housekeeping

#3068 Fix flaky dvc.focusedProjects test
  extension/src/test/suite/config.test.ts
Labels: 🏠 housekeeping

#3069 Fix flaky smooth plot panel test
  webview/src/plots/components/App.test.tsx
Labels: 🏠 housekeeping

#3074 Extend timeout of cross-platform-test to 25 minutes
  .github/workflows/cross-platform-test.yml
Labels: 🏠 housekeeping

#3059 Create queue workers in background process
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/cli/dvc/index.ts
  extension/src/cli/index.ts
  extension/src/processExecution.ts
  extension/src/test/suite/cli/background.ts
  extension/src/test/suite/cli/child.ts
  extension/src/test/suite/cli/index.test.ts
  extension/src/test/suite/cli/util.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/fileSystem/data/index.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/test/util/jest/index.ts
Labels: bug

#3073 Add remove tasks from queue command
  extension/package.json
  extension/package.nls.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/model/util.ts
  extension/src/experiments/quickPick.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/title.ts
Labels: product

#3079 Use Chromatic's Turbosnap functionality
  .github/workflows/continuous-integration.yml
  package.json
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3081 Remove setup triggered count from test altogether
  extension/src/test/suite/config.test.ts
Labels: 🏠 housekeeping

#3080 Only render smooth template for unit tests
  webview/src/plots/components/App.test.tsx
Labels: 🏠 housekeeping

#3082 Drop custom script from actions (use yarn install)
  .github/workflows/end-to-end-test.yml
  .github/workflows/publish.yml
Labels: 🏠 housekeeping

#3083 Move pick experiments quick pick
  extension/src/experiments/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/experiments/quickPick.test.ts
  extension/src/experiments/quickPick.ts
Labels: 🏠 housekeeping

#3084 Add kill experiments queue tasks command
  extension/package.json
  extension/package.nls.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/title.ts
Labels: product

#3087 Add "Previous Commits" row to experiments table
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/pageObjects/locators.ts
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#3089 Increase timeout of smooth plot test (Windows CI)
  webview/src/plots/components/App.test.tsx
Labels: 🏠 housekeeping

#3107 Revert "Update version and CHANGELOG for release"
  CHANGELOG.md
  extension/package.json
Labels: 🏠 housekeeping

#3108 Fix typo in plots tooltip
  webview/src/plots/components/PlotsContainer.tsx
Labels: bug

#3105 Add experiment row commit tooltips
  extension/src/cli/git/constants.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/webview/contract.ts
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/stories/util.ts
Labels: product

#3110 Add `workflow_dispatch` event to `publish` workflow
  .github/workflows/publish.yml
Labels: 🏠 housekeeping

#3113 Make experiment row commit tooltips interactive
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/util/helpers.ts
  webview/src/util/props.ts
Labels: product

#3114 Show commits in "Select Experiments to Display in Plots" quick pick
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
Labels: product

#3129 Update Windows yarn network timeout to 5 minutes (downloading packages on slow disk)
  .github/workflows/cross-platform-test.yml
Labels: 🏠 housekeeping

#3128 Add resolution for json5 library (security)
  package.json
  yarn.lock
Labels: 🏠 housekeeping

#3122 Add commit message to plots ribbon block tooltips
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/plots/components/ribbon/RibbonBlockTooltip.tsx
  webview/src/plots/components/ribbon/styles.module.scss
  webview/src/shared/components/icons/GitCommit.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/stories/Ribbon.stories.tsx
Labels: product

#3124 Add `git-commit` icon to experiments table and quick pick
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
  webview/src/experiments/components/table/CellSecondaryName.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#3095 Upgrade react-table
  .codeclimate.json
  extension/src/experiments/webview/contract.ts
  extension/src/test/e2e/pageObjects/locators.ts
  webview/package.json
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Cell.tsx
  webview/src/experiments/components/table/CellHintTooltip.tsx
  webview/src/experiments/components/table/CellRowActions.tsx
  webview/src/experiments/components/table/Errors.tsx
  webview/src/experiments/components/table/ExperimentGroup.tsx
  webview/src/experiments/components/table/NestedRow.tsx
  webview/src/experiments/components/table/Row.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/content/Cell.tsx
  webview/src/experiments/components/table/content/CellContent.tsx
  webview/src/experiments/components/table/content/CellTooltip.tsx
  webview/src/experiments/components/table/content/DateCellContent.tsx
  webview/src/experiments/components/table/content/ErrorCell.tsx
  webview/src/experiments/components/table/content/Header.tsx
  webview/src/experiments/components/table/content/TimestampHeader.tsx
  webview/src/experiments/components/table/content/UndefinedCell.tsx
  webview/src/experiments/components/table/header/ColumnResizer.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/headersSlice.ts
  webview/src/experiments/components/table/interfaces.ts
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/hooks/useColumnOrder.test.ts
  webview/src/experiments/hooks/useColumnOrder.ts
  webview/src/experiments/react-table-config.d.ts
  webview/src/experiments/util/buildColumns.tsx
  webview/src/experiments/util/buildDynamicColumns.test.ts
  webview/src/experiments/util/buildDynamicColumns.tsx
  webview/src/experiments/util/columns.ts
  webview/src/experiments/util/rows.ts
  webview/src/test/sort.ts
  yarn.lock
Labels: 🏠 housekeeping

#3156 Fix Experiments table multi-select context menu
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: bug

#3153 Ensure dvc roots are not duplicated during collection
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/setup/index.ts
Labels: bug

#3154 Update user facing queue terminology
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#3158 Refactor and reduce code in context class
  extension/src/context.ts
Labels: 🏠 housekeeping

#3163 Fix test describe statements
  extension/src/test/suite/config.test.ts
Labels: 🏠 housekeeping

#3165 Recheck for global and venv dvc version
  extension/src/cli/dvc/discovery.ts
  extension/src/setup/index.ts
  extension/src/setup/runner.test.ts
  extension/src/setup/runner.ts
  extension/src/test/suite/setup/util.ts
Labels: bug

#3166 Combine remove experiments and remove queued experiment quick picks
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: product

#3167 Replace branch terminology with commit for Experiments internals
  extension/package.json
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/extract.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/accumulator.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/test/fixtures/expShow/base/noErrors.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/fixtures/plotsDiff/util.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/util/jest/index.ts
  webview/src/experiments/components/App.test.tsx
Labels: 🏠 housekeeping

#3174 Fix inital ordering of experiments table
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/util/buildColumns.tsx
Labels: bug

#3168 Add stop queued experiment running option into table context menu
  extension/src/commands/external.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: product

#3175 Implement simple onDefinition feature in LSP
  extension/src/extension.ts
  extension/src/fileSystem/index.ts
  extension/src/lspClient/languageClient.ts
  extension/src/test/suite/fileSystem/index.test.ts
  languageServer/src/LanguageServer.ts
  languageServer/src/TextDocumentWrapper.ts
  languageServer/src/regexes.ts
  languageServer/src/test/definitions.test.ts
  languageServer/src/test/fixtures/examples/valid/index.ts
  languageServer/src/test/fixtures/python/index.ts
  languageServer/src/test/utils/openTheseFilesAndNotifyServer.ts
  languageServer/src/test/utils/requestDefinitions.ts
  languageServer/src/test/utils/sendTheseFilesToServer.ts
  languageServer/src/test/utils/setup-test-connections.ts
Labels: product

#3185 Rename files associated with LSP
  extension/src/extension.ts
  extension/src/languageClient/index.ts
  languageServer/src/TextDocumentWrapper.ts
  languageServer/src/languageServer.ts
  languageServer/src/server.ts
  languageServer/src/test/utils/setup-test-connections.ts
  languageServer/src/textDocument.ts
Labels: 🏠 housekeeping
