Repository iterative/vscode-dvc, pull requests merged in 2023-11, with the labels that each got.

#4955 Fix e2e tests (SCM entry removed by insiders)
  extension/src/test/e2e/extension.test.ts
  extension/src/test/e2e/util.ts
  extension/src/test/e2e/wdio.conf.ts
Labels: bug

#4960 Add style to plots in drag and drop mode
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/paths.ts
  extension/src/plots/model/custom.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/DragAndDropGrid.tsx
  webview/src/plots/components/DragAndDropPlot.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/util.ts
Labels: product

#4942 Seamless drag and drop mode
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/paths.ts
  extension/src/plots/model/custom.ts
  webview/icons/codicons.mjs
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/DragAndDropGrid.tsx
  webview/src/plots/components/DragAndDropPlot.tsx
  webview/src/plots/components/Grid.tsx
  webview/src/plots/components/NormalGrid.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/util.ts
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DragDropItem.tsx
  webview/src/shared/components/dragDrop/GripIcon.tsx
  webview/src/shared/components/icons/Move.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#4934 Add drag and drop mode to plots
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/paths.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/custom.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/DragAndDropGrid.tsx
  webview/src/plots/components/DragAndDropPlot.tsx
  webview/src/plots/components/Grid.tsx
  webview/src/plots/components/NormalGrid.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/PlotsPicker.tsx
  webview/src/plots/components/SizeSliders.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/customPlots/CustomPlot.tsx
  webview/src/plots/components/customPlots/CustomPlots.tsx
  webview/src/plots/components/customPlots/CustomPlotsWrapper.tsx
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/util.ts
  webview/src/plots/hooks/useGetPlot.ts
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DragDropItem.tsx
  webview/src/shared/components/dragDrop/GripIcon.tsx
  webview/src/shared/components/iconMenu/IconMenuItem.tsx
  webview/src/shared/components/selectMenu/MultiSelect.tsx
Labels: product, do not merge

#4987 Update webview test timeout
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#5009 Revert @vscode/extension-telemetry to 0.8.5
  extension/package.json
  yarn.lock
Labels: 🏠 housekeeping

#5017 Add drag and drop mode to comparison table headers
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/util.ts
Labels: product

#5000 Add progress indicator when fetching a studio token
  extension/src/setup/studio.ts
  extension/src/test/suite/setup/index.test.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/studio/Connect.tsx
Labels: product

#5025 Do not render section if it is not open
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/customPlots/customPlotsSlice.ts
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/util.ts
  webview/src/plots/util/messages.ts
  webview/src/setup/components/App.test.tsx
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
Labels: 🏠 housekeeping

#5020 Select 20 plots by default per section
  extension/src/path/selection/model.ts
  extension/src/plots/index.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/model.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/App.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/TooManyPlots.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/shared/components/messageBand/MessageBand.test.tsx
  webview/src/shared/components/messageBand/MessageBand.tsx
  webview/src/shared/components/messageBand/styles.module.scss
Labels: product

#5041 Collect columns from experiments under baseline with error
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
Labels: bug

#5047 Use parent ref to appropriately size plot titles
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/vegaLite/ExtendedVegaLite.tsx
  webview/src/plots/components/vegaLite/util.test.ts
  webview/src/plots/components/vegaLite/util.ts
  webview/src/plots/hooks/useGetPlot.ts
Labels: product

#5030 Extend available workspace params available to modify
  extension/src/experiments/model/modify/collect.test.ts
  extension/src/experiments/model/modify/collect.ts
  extension/src/experiments/model/modify/quickPick.ts
Labels: product
