Repository iterative/vscode-dvc, pull requests merged in 2023-10, with the labels that each got.

#4735 Collapse duplicate rows when table is flattened
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/sorted/rows.ts
  extension/src/test/fixtures/expShow/sorted/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/content/BranchCellContent.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#4762 Handle pull requests from forks
  .github/workflows/continuous-integration.yml
Labels: 🏠 housekeeping

#4748 Allow Multi File Select on Plot Wizard
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
  extension/src/plots/quickPick.test.ts
  extension/src/plots/quickPick.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/vscode/resourcePicker.test.ts
  extension/src/vscode/resourcePicker.ts
  extension/src/vscode/title.ts
Labels: product

#4769 Remove unused function
  extension/src/fileSystem/workspace.ts
Labels: 🏠 housekeeping

#4768 Add remove as inline SCM action for added resources
  extension/package.json
  extension/src/repository/model/tree.ts
  extension/src/test/suite/repository/model/tree.test.ts
Labels: product

#4783 Transfer selection/starred status to renamed experiment
  extension/src/experiments/commands/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: bug

#4784 Watch deps and outs files for experiment updates
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/data/collect.ts
Labels: 🏠 housekeeping

#4794 Add subscribe to YouTube message to README
  README.md
Labels: 🏠 housekeeping

#4795 Remove banner from README
  README.md
  extension/resources/banner.png
Labels: 🏠 housekeeping

#4806 Added webdriverio-monorepo to ignored dependencies for Renovate
  renovate.json
Labels: 🏠 housekeeping

#4808 Fix error when user chooses no Y fields in the Plot Wizard
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
Labels: bug

#4819 Ignore every WebdriverIO dependency in Renovate
  renovate.json
Labels: 🏠 housekeeping

#4823 Ignore new .turbo directory
  .gitignore
Labels: 🏠 housekeeping

#4798 Add error handling for Plot Wizard plots with x fields
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
Labels: bug

#4797 Add Multiple X Field Selection to Plot Wizard
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/test/suite/vscode/quickPick.test.ts
  extension/src/vscode/quickPick.ts
Labels: product

#4810 Deeply nested repo
  extension/src/cli/dvc/constants.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/setup/index.ts
  extension/src/test/suite/setup/util.ts
Labels: product

#4827 Improve validation of Plot Wizard Y metrics quick pick
  extension/src/pipeline/quickPick.test.ts
  extension/src/pipeline/quickPick.ts
  extension/src/test/suite/util.ts
  extension/src/test/suite/vscode/quickPick.test.ts
  extension/src/vscode/quickPick.ts
  extension/src/vscode/title.ts
Labels: product

#4837 Rename "Save" to "Save Token" in studio settings
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/studio/Connect.tsx
Labels: product

#4793 Update "No Plots" section message
  extension/package.json
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.tsx
  webview/src/plots/components/emptyState/AddPlots.tsx
  webview/src/plots/components/emptyState/ErrorState.tsx
  webview/src/plots/components/emptyState/WaitForPlotsInfo.tsx
  webview/src/plots/components/emptyState/styles.module.scss
  webview/src/plots/components/templatePlots/NoPlotsToDisplay.tsx
Labels: product

#4847 Update DVCLive XGBoost snippet
  extension/snippets/dvclive.code-snippets
Labels: product

#4835 Fix exporting plots to SVG
  extension/src/fileSystem/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/constants.ts
  webview/src/plots/components/templatePlots/TemplateVegaLite.tsx
  webview/src/plots/util/messages.ts
  webview/src/util/styles.test.ts
  webview/src/util/styles.ts
Labels: bug

#4849 Update default export path for plots data
  extension/src/plots/webview/messages.ts
Labels: 🏠 housekeeping

#4845 Add `Add Plot` command to walkthrough
  extension/resources/walkthrough/plots.md
Labels: product

#4853 Fix DVCLive snippet in walkthrough
  extension/resources/walkthrough/live-plots.md
Labels: 🏠 housekeeping

#4852 Amend changelog with missing entry
  CHANGELOG.md
Labels: 🏠 housekeeping

#4869 Warn user before trying to add a stage to their pipeline
  extension/src/experiments/webview/messages.ts
  extension/src/pipeline/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/test/suite/pipeline/util.ts
Labels: bug

#4879 Fix `quickPickUserOrderedValues` windows test timing out
  extension/src/test/suite/vscode/quickPick.test.ts
Labels: 🏠 housekeeping

#4857 Add created branch (from `dvc exp branch`) to the experiments table
  extension/src/experiments/commands/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
Labels: product

#4898 Remove @types/react-measure
  webview/package.json
  yarn.lock
Labels: 🏠 housekeeping

#4882 Add tags filters to experiments table
  extension/src/experiments/columns/like.ts
  extension/src/experiments/columns/quickPick.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/index.test.ts
  extension/src/experiments/model/filterBy/index.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/test/fixtures/expShow/base/gitLog.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/filterBy/util.ts
Labels: product

#4911 Watch Git tags for experiment table updates
  extension/src/cli/git/constants.ts
  extension/src/experiments/data/index.ts
Labels: product

#4900 Fix unstable `quickPickUserOrderedValues` test in windows
  extension/src/test/suite/util.ts
  extension/src/test/suite/vscode/quickPick.test.ts
Labels: 🏠 housekeeping

#4880 Split drag and drop container into different files
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/shared/components/dragDrop/DragDropContainer.tsx
  webview/src/shared/components/dragDrop/DragDropItem.tsx
  webview/src/shared/components/dragDrop/DragDropItemWithTarget.tsx
  webview/src/shared/components/dragDrop/util.ts
  webview/src/test/dragDrop.ts
Labels: 🏠 housekeeping

#4904 Remove check for stages in plot wizard
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/index.ts
  extension/src/test/suite/pipeline/index.test.ts
Labels: product

#4923 Increase plot webview test timeout
  extension/src/test/suite/plots/index.test.ts
Labels: 🏠 housekeeping

#4928 Increase timeouts of webview tests
  extension/src/test/suite/plots/index.test.ts
Labels: 🏠 housekeeping

#4930 Remove unused dependencies
  package.json
  yarn.lock
Labels: 🏠 housekeeping
