Repository iterative/vscode-dvc, pull requests merged in 2023-02, with the labels that each got.

#3184 Remove unnecessary dependencies from LSP
  languageServer/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3181 Remove unnecessary interface from LSP
  languageServer/src/ITextDocumentWrapper.ts
Labels: 🏠 housekeeping

#3194 Limit language server reach to dvc yaml files
  extension/src/languageClient/index.ts
  languageServer/src/documentSelector.ts
  languageServer/src/languageServer.ts
Labels: bug

#3191 Fix table/plots not updating correctly on windows
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/fileSystem/data/index.ts
  extension/src/fileSystem/relativePattern.ts
  extension/src/fileSystem/watcher.ts
  extension/src/repository/data/index.ts
  extension/src/setup/index.ts
  extension/src/test/suite/fileSystem/watcher.test.ts
Labels: bug

#3192 Fix minor table bugs
  webview/src/experiments/components/table/TableBody.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#3198 Remove read file contents request sent to extension by language server (use is file check)
  extension/src/fileSystem/index.ts
  extension/src/languageClient/index.ts
  extension/src/test/suite/fileSystem/index.test.ts
  languageServer/src/languageServer.ts
  languageServer/src/test/definitions.test.ts
  languageServer/src/test/utils/setup-test-connections.ts
  languageServer/src/textDocument.ts
Labels: 🏠 housekeeping

#3205 Remove beaker (show experiments) and scatter graph (show plots) buttons from sidebar
  extension/package.json
Labels: product

#3206 Add a mention to run script after adding dvclive
  webview/src/setup/components/NoData.tsx
Labels: product

#3208 Add project level jest config (for WallabyJS)
  jest.config.js
Labels: 🏠 housekeeping

#3212 Fix missing button
  extension/package.json
Labels: bug

#3227 Increase timeout of tests which use window.withProgress
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/setup/autoInstall.test.ts
  extension/src/test/suite/timeouts.ts
Labels: 🏠 housekeeping

#3197 Create dvc.yaml file with training script on run experiment
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/title.ts
Labels: product

#3239 Add reminder to commit after `dvc init`
  extension/src/setup/index.ts
Labels: product

#3241 Don't add "Created" column when there is no data
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/model.test.ts
Labels: bug

#3201 Attempt to fix flaky integration test (simplify and split)
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#3240 Add jupyter notebook script to run in dvc.yaml
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: product

#3250 Improve vega bindings color (smooth template)
  webview/src/plots/components/styles.module.scss
Labels: product

#3247 Add ability to stop experiments running in the workspace (outside of the extension)
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/context.ts
  extension/src/experiments/index.ts
  extension/src/experiments/processes/collect.test.ts
  extension/src/experiments/processes/collect.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/fileSystem/index.ts
  extension/src/test/suite/context.test.ts
  extension/src/util/number.test.ts
  extension/src/vscode/context.ts
Labels: product

#3248 Remove unnecessary dependency from tests
  extension/src/test/suite/plots/data/index.test.ts
Labels: 🏠 housekeeping

#3252 Ask the user for the stage name to add to pipeline
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/vscode/inputBox.ts
  extension/src/vscode/title.ts
Labels: product

#3242 Open dvc.yaml automatically after adding a pipeline
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: product

#3253 Show a setup screen when project has no commits
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.tsx
  webview/src/setup/components/NeedsGitCommit.tsx
  webview/src/stories/NeedsGitCommit.stories.tsx
Labels: product

#3244 Fix package-manager issue
  CONTRIBUTING.md
  package.json
Labels: bug

#3249 Add ability to stop non-queue experiments from the table's context menu
  extension/src/experiments/processExecution/collect.test.ts
  extension/src/experiments/processExecution/collect.ts
  extension/src/experiments/processExecution/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/extension.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: product

#3257 Add the script as a dependency in dvc.yaml
  extension/src/fileSystem/index.ts
Labels: product

#3255 Ask the user for the correct command to their script if it is neither a python file or a Jupyter notebook
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/vscode/title.ts
Labels: product

#3261 Add missing telemetry events to onboarding
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
Labels: 🏠 housekeeping

#3259 Add regression test for `.git` file watcher
  extension/src/test/suite/experiments/data/index.test.ts
Labels: 🏠 housekeeping

#3256 Show the setup instead of original webview if needed (command palette)
  extension/package.json
  extension/src/commands/util.ts
  extension/src/experiments/commands/register.ts
  extension/src/extension.ts
  extension/src/plots/commands/register.ts
  extension/src/setup/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
Labels: product

#3271 Fix checkboxes unchecking when user clicks outside the table
  webview/src/experiments/components/table/Table.tsx
  webview/src/shared/hooks/useClickOutside.ts
Labels: bug

#3272 Replace Show Experiments and Plots buttonwith a Run Experiment button and added icons to sidebar buttons
  extension/package.json
Labels: product

#3275 Rename views tree to actions
  extension/package.json
Labels: product

#3280 Correctly debounce resize of table columns
  webview/package.json
  webview/src/experiments/components/Experiments.tsx
  yarn.lock
Labels: bug

#3291 Move the comparison table header down from under the ribbon when scrolling
  webview/src/plots/components/comparisonTable/ComparisonTableHead.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/ribbonSlice.ts
  webview/src/plots/store.ts
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/Plots.stories.tsx
Labels: bug

#3281 Add add configuration button in experiments table
  extension/src/experiments/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/util.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/components/table/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
Labels: product

#3235 Enable saving of Studio access token
  .vscode/settings.json
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/connect/index.ts
  extension/src/connect/inputBox.test.ts
  extension/src/connect/inputBox.ts
  extension/src/connect/register.ts
  extension/src/connect/token.ts
  extension/src/connect/webview/contract.ts
  extension/src/extension.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/connect/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/vscode/context.ts
  extension/src/vscode/external.ts
  extension/src/vscode/inputBox.ts
  extension/src/vscode/modal.ts
  extension/src/vscode/title.ts
  extension/src/webview/constants.ts
  extension/src/webview/contract.ts
  extension/src/webview/repository.ts
  webview/.eslintrc.js
  webview/index.d.ts
  webview/index.js
  webview/src/connect/components/App.test.tsx
  webview/src/connect/components/App.tsx
  webview/src/connect/components/Studio.tsx
  webview/src/connect/components/messages.ts
  webview/src/connect/index.tsx
  webview/src/shared/hooks/useVsCodeMessaging.ts
  webview/src/stories/Connect.stories.tsx
  webview/webpack.config.ts
Labels: product

#3289 Share experiment to Studio from experiments table
  extension/package.json
  extension/package.nls.json
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.ts
  extension/src/commands/external.ts
  extension/src/commands/internal.ts
  extension/src/connect/index.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/extension.ts
  extension/src/patch.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/patch.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
  yarn.lock
Labels: product

#3294 Create Modal class (mirror Toast)
  extension/src/cli/dvc/actions.ts
  extension/src/connect/index.ts
  extension/src/repository/commands/index.test.ts
  extension/src/repository/commands/index.ts
  extension/src/repository/model/tree.ts
  extension/src/vscode/modal.test.ts
  extension/src/vscode/modal.ts
Labels: 🏠 housekeeping

#3277 Clean up webview factory
  extension/src/connect/index.ts
  extension/src/setup/index.ts
  extension/src/webview/contract.ts
  extension/src/webview/factory.ts
  extension/src/webview/repository.ts
Labels: 🏠 housekeeping

#3299 Ensure that file exists before trying to read mtime
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: bug

#3300 Ensure DVC tracked tree is rebuilt when a dvc yaml error has been fixed
  extension/src/repository/index.ts
  extension/src/repository/model/decorationProvider.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
Labels: bug

#3303 Update get Studio access token link
  extension/src/connect/index.ts
  extension/src/test/suite/connect/index.test.ts
Labels: product

#3309 fix: DnD landing breaks on ellipsis
  webview/src/experiments/components/table/styles.module.scss
Labels: bug, A: table

#3306 Update link to get Studio access token (drop need for username)
  extension/src/connect/index.ts
  extension/src/test/suite/connect/index.test.ts
Labels: product

#3295 Change the add configuration button text and add more information on functionality
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: product

#3310 Disable unnecessary chromatic snapshots
  webview/src/stories/CliIncompatible.stories.tsx
  webview/src/stories/CliUnavailable.stories.tsx
  webview/src/stories/ComparisonTable.stories.tsx
  webview/src/stories/ComparisonTableHeader.stories.tsx
  webview/src/stories/Connect.stories.tsx
  webview/src/stories/ContextMenu.stories.tsx
  webview/src/stories/IconMenu.stories.tsx
  webview/src/stories/NeedsGitCommit.stories.tsx
  webview/src/stories/Plots.stories.tsx
  webview/src/stories/ProjectUninitialized.stories.tsx
  webview/src/stories/Ribbon.stories.tsx
  webview/src/stories/Tooltip.stories.tsx
  webview/src/stories/util.ts
Labels: 🏠 housekeeping

#3311 Redirect user to add new Studio access token on 401 response
  extension/src/patch.ts
  extension/src/test/suite/patch.test.ts
  extension/src/vscode/modal.ts
Labels: product

#3314 Re-add show experiments and show plots to tree view titles
  extension/package.json
Labels: product

#3315 Remove auto apply filters to experiment selection for plots
  README.md
  extension/package.json
  extension/package.nls.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/tree.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/toast.test.ts
  extension/src/experiments/toast.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/vscode/config.ts
  extension/src/vscode/context.ts
Labels: product

#3319 Add metrics.json to plots list of watched files
  extension/src/plots/data/index.ts
Labels: bug

#3304 Check stages for all run/queue commands
  extension/src/experiments/commands/register.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/extension.test.ts
Labels: product

#3321 Watch metric files to update plots
  extension/src/plots/data/collect.test.ts
  extension/src/plots/data/collect.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/test/suite/plots/data/index.test.ts
Labels: bug, A: codespaces

#3323 Direct user to setup when they cannot run an experiment
  extension/package.json
  extension/src/experiments/commands/register.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: bug

#3339 Remove legacy todo
  extension/src/webview/index.ts
Labels: 🏠 housekeeping

#3341 Optimize the plots sections to reduce the number of useless re-renderings
  webview/src/plots/components/templatePlots/TemplatePlots.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
Labels: 🏠 housekeeping

#3346 Improve naming in experiment row context menu component
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: 🏠 housekeeping

#3348 Clean up from optimizing rendering of plots
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlot.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
Labels: 🏠 housekeeping

#3355 Update prototype stub (flaky test)
  extension/src/test/suite/extension.test.ts
Labels: 🏠 housekeeping

#3356 Group process execution and manager
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/cli/dvc/options.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/runner.ts
  extension/src/cli/error.ts
  extension/src/cli/git/executor.test.ts
  extension/src/cli/git/options.ts
  extension/src/cli/index.ts
  extension/src/data/index.ts
  extension/src/experiments/processExecution/index.ts
  extension/src/extension.ts
  extension/src/extensions/python.test.ts
  extension/src/fileSystem/index.ts
  extension/src/process/execution.test.ts
  extension/src/process/execution.ts
  extension/src/process/manager.ts
  extension/src/python/index.test.ts
  extension/src/python/index.ts
  extension/src/repository/data/index.ts
  extension/src/setup/runner.test.ts
  extension/src/test/suite/cli/index.test.ts
  extension/src/test/suite/cli/util.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/process/manager.test.ts
  extension/src/test/suite/util.ts
  extension/src/test/util/jest/index.ts
Labels: 🏠 housekeeping

#3358 Add viewable cli process class
  extension/src/cli/dvc/runner.ts
  extension/src/cli/index.ts
  extension/src/cli/util.ts
  extension/src/cli/viewable.ts
  extension/src/telemetry/constants.ts
  extension/src/telemetry/index.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
  extension/src/test/suite/cli/viewable.test.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3359 Add DvcViewer class
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/runner.ts
  extension/src/cli/dvc/viewer.ts
  extension/src/cli/viewable.ts
  extension/src/commands/internal.ts
  extension/src/extension.ts
  extension/src/test/suite/cli/dvc/viewer.test.ts
  extension/src/vscode/pseudoTerminal.ts
Labels: 🏠 housekeeping

#3361 Remove legacy test code from DvcRunner
  extension/src/cli/dvc/runner.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
Labels: 🏠 housekeeping

#3362 Remove legacy code from PseudoTerminal
  extension/src/test/suite/vscode/pseudoTerminal.test.ts
  extension/src/vscode/pseudoTerminal.ts
Labels: 🏠 housekeeping

#3371 Move e2e tests to stable (wdio chromedriver issue)
  extension/src/test/e2e/wdio.conf.ts
Labels: 🏠 housekeeping

#3360 Add show logs to context menu of experiments running in the queue
  extension/package.json
  extension/package.nls.json
  extension/src/cli/dvc/viewer.ts
  extension/src/cli/viewable.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/util.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/RowContextMenu.tsx
Labels: product

#3367 Delete unused code in Plots
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/checkpointPlots/CheckpointPlotsWrapper.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableWrapper.tsx
  webview/src/plots/components/templatePlots/TemplatePlotsWrapper.tsx
Labels: 🏠 housekeeping

#3369 Remove hortizontal scrollbar from empty section
  webview/src/shared/components/emptyState/styles.module.scss
Labels: bug
