Repository iterative/vscode-dvc, pull requests merged in 2023-05, with the labels that each got.

#3791 Display progress errors to users
  extension/src/setup/autoInstall.ts
  extension/src/test/suite/setup/autoInstall.test.ts
  extension/src/vscode/toast.ts
Labels: bug

#3781 Integrate remaining share experiment command with the extension (exp push)
  README.md
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/config.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: product

#3792 Add multi-select versions of exp push
  extension/package.json
  extension/src/experiments/commands/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: product

#3793 Add push experiment(s) to the command palette
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/title.ts
Labels: product

#3787 Fix dvc details version incorrectly showing "Not Found"
  extension/src/cli/dvc/discovery.ts
  extension/src/interfaces.ts
  extension/src/setup/index.ts
  extension/src/setup/runner.test.ts
  extension/src/setup/runner.ts
  extension/src/test/suite/setup/index.test.ts
Labels: bug

#3797 WorkspaceExperiments housekeeping
  extension/src/experiments/workspace.ts
Labels: 🏠 housekeeping

#3799 Wait for config to be ready before accessing values
  extension/src/config.ts
  extension/src/setup/index.ts
  extension/src/test/suite/setup/index.test.ts
Labels: 🏠 housekeeping

#3801 Fix missing tracked decorations
  extension/src/repository/model/collect.test.ts
  extension/src/repository/model/collect.ts
Labels: bug

#3808 Hide push option when an experiment is running
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: bug

#3807 Add stylelint to precommit hook
  webview/.lintstagedrc.js
Labels: 🏠 housekeeping

#3784 Simplify DVC CLI Location/Version Logic
  extension/src/cli/dvc/discovery.ts
  extension/src/cli/dvc/version.test.ts
  extension/src/cli/dvc/version.ts
  extension/src/setup/runner.test.ts
  extension/src/status.ts
  extension/src/test/suite/status.test.ts
Labels: product

#3815 Remove pausing of data updates when running/queueing experiments
  extension/src/data/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/workspace.ts
  extension/src/process/manager.ts
  extension/src/repository/data/index.ts
  extension/src/repository/index.ts
  extension/src/repository/workspace.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/process/manager.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/test/suite/util.ts
  extension/src/workspace/index.ts
Labels: product

#3825 Keep experiments table context menu consistent by showing disabled items
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/ExperimentGroup.tsx
  webview/src/experiments/components/table/body/NestedRow.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/util/interfaces.ts
  webview/src/shared/components/contextMenu/ContextMenu.tsx
  webview/src/shared/components/messagesMenu/MessagesMenu.tsx
  webview/src/shared/components/messagesMenu/MessagesMenuOption.tsx
  webview/src/shared/components/messagesMenu/styles.module.scss
  webview/src/shared/variables.scss
  webview/src/util/props.ts
Labels: product

#3826 Add import/no-unused-modules rule to eslint config
  .eslintrc.js
  extension/src/cli/dvc/discovery.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/paths.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/colors.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/plots/index.ts
  extension/src/plots/multiSource/constants.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/vega/util.ts
  extension/src/repository/model/collect.ts
  extension/src/repository/model/error.ts
  extension/src/setup/index.ts
  extension/src/setup/token.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
  extension/src/tree/index.ts
  extension/src/util/map.ts
  extension/src/vscode/workspace.ts
  extension/src/webview/contract.ts
  languageServer/src/documentSelector.ts
  languageServer/src/test/utils/setup-test-connections.ts
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/body/CellHintTooltip.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
  webview/src/experiments/components/table/content/Cell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/plots/components/GetStarted.tsx
  webview/src/plots/components/PlotsContainer.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/ribbon/RibbonBlock.tsx
  webview/src/setup/components/Experiments.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/Dvc.tsx
  webview/src/setup/components/dvc/ProjectUninitialized.tsx
  webview/src/shared/api.ts
  webview/src/shared/components/button/IconButton.tsx
  webview/src/shared/components/dragDrop/Draggable.tsx
  webview/src/shared/components/getStarted/GetStarted.tsx
  webview/src/shared/components/iconMenu/IconMenuItem.tsx
  webview/src/shared/components/messagesMenu/MessagesMenu.tsx
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/selectMenu/SelectMenu.tsx
  webview/src/test/dragDrop.ts
  webview/src/test/experimentsTable.tsx
  webview/src/test/sort.ts
  webview/src/test/tableDataFixture.ts
  webview/src/util/objects.ts
Labels: 🏠 housekeeping

#3833 Increase default width and decrease min width of experiments column
  webview/src/experiments/components/Experiments.tsx
Labels: 🏠 housekeeping

#3831 Ensure that accessing the DVC config doesn't throw an error
  extension/src/setup/index.ts
Labels: bug

#3823 Add completion status to setup sections
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/SetupContainer.tsx
  webview/src/shared/components/icons/PassFilled.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/shared/components/sectionContainer/InfoTooltip.tsx
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/variables.scss
  webview/src/stories/Icons.stories.tsx
  webview/src/stories/Setup.stories.tsx
Labels: product

#3832 Enable experiment operations when experiment(s) are running in the queue
  extension/package.json
  extension/src/context.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/context.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/vscode/context.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/body/ExperimentGroup.tsx
  webview/src/experiments/components/table/body/NestedRow.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/interfaces.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
  webview/src/test/sort.ts
Labels: product

#3834 Enable running exp apply and exp branch against commits
  extension/package.json
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/workspace.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/test/experimentsTable.tsx
Labels: product

#3846 Prevent queued experiment from being selected as most recent
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
Labels: bug

#3840 Combine/enhance commands used to stop experiments
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/processExecution/collect.ts
  extension/src/experiments/processExecution/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/util/number.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: product

#3855 Update all webdriver packages
  extension/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3850 Update DVC Setup Version Details
  extension/src/cli/dvc/discovery.ts
  extension/src/cli/dvc/version.test.ts
  extension/src/cli/dvc/version.ts
  extension/src/setup/runner.test.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/dvc/DvcEnvDetails.tsx
Labels: product

#3859 Update coverage path ignore patterns
  extension/jest.config.js
  extension/src/test/suite/index.ts
  languageServer/jest.config.js
  webview/jest.config.js
Labels: 🏠 housekeeping

#3857 Send all stderr and stdout to the output channel when a DVC process fails
  extension/src/cli/dvc/runner.ts
  extension/src/cli/index.ts
  extension/src/cli/util.ts
  extension/src/cli/viewable.ts
  extension/src/test/suite/cli/failed.ts
  extension/src/test/suite/cli/index.test.ts
  extension/src/test/suite/cli/util.ts
  extension/src/test/suite/vscode/outputChannel.test.ts
  extension/src/vscode/outputChannel.ts
Labels: product

#3858 Update CodeClimate exclude patterns
  .codeclimate.json
Labels: 🏠 housekeeping

#3851 Add redux to setup webview
  extension/src/setup/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/Experiments.tsx
  webview/src/setup/components/SetupContainer.tsx
  webview/src/setup/components/dvc/Dvc.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/experiments/NeedsGitCommit.tsx
  webview/src/setup/components/experiments/NoData.tsx
  webview/src/setup/components/studio/CliIncompatible.tsx
  webview/src/setup/components/studio/Studio.tsx
  webview/src/setup/index.tsx
  webview/src/setup/state/dvcSlice.ts
  webview/src/setup/state/experimentsSlice.ts
  webview/src/setup/state/studioSlice.ts
  webview/src/setup/state/webviewSlice.ts
  webview/src/setup/store.ts
Labels: 🏠 housekeeping

#3862 Lower setup section prop drilling
  webview/src/setup/components/dvc/CliIncompatible.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/Dvc.tsx
  webview/src/setup/components/dvc/DvcEnvCommandRow.tsx
  webview/src/setup/components/dvc/DvcEnvDetails.tsx
  webview/src/setup/components/dvc/DvcUnitialized.tsx
  webview/src/setup/components/dvc/GitUnitialized.tsx
  webview/src/setup/components/dvc/ProjectUninitialized.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/experiments/NeedsGitCommit.tsx
  webview/src/setup/components/studio/Settings.tsx
  webview/src/setup/components/studio/Studio.tsx
  webview/src/setup/state/webviewSlice.ts
Labels: 🏠 housekeeping

#3856 Update blocked ESM only packages (execa, process-exists)
  extension/package.json
  extension/scripts/coverIntegrationTests.js
  extension/scripts/virtualenv-install.js
  extension/src/extension.ts
  extension/src/process/execution.test.ts
  extension/src/process/execution.ts
  extension/src/python/index.test.ts
  extension/src/python/index.ts
  extension/src/test/cli/index.ts
  extension/src/test/e2e/util.ts
  extension/src/test/suite/cli/child.ts
  extension/src/test/suite/process/execution.test.ts
  extension/src/util/esm.ts
  extension/tsconfig.json
  package.json
  renovate.json
  scripts/virtualenv-install.ts
  yarn.lock
Labels: 🏠 housekeeping

#3874 Add available codicons to Storybook
  webview/src/stories/Icons.stories.tsx
Labels: 🏠 housekeeping

#3873 Automatically add new icons to the icons story in Storybook
  CONTRIBUTING.md
  webview/src/stories/Icons.stories.tsx
Labels: 🏠 housekeeping

#3876 Simplify table data fixtures
  extension/src/test/fixtures/expShow/base/workspaceChanges.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/fixtures/expShow/survival/tableData.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  webview/src/test/sort.ts
Labels: 🏠 housekeeping

#3892 Remove node-fetch as a dependency (not used)
  extension/package.json
  yarn.lock
Labels: 🏠 housekeeping

#3887 Debounce calls to git branch
  extension/src/experiments/data/index.ts
Labels: bug

#3896 Fix broken setup stories
  webview/src/setup/components/App.tsx
  webview/src/stories/Setup.stories.tsx
Labels: 🏠 housekeeping

#3827 Call exp show with multiple branches
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/sortBy/index.test.ts
  extension/src/experiments/model/status/index.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/test/fixtures/expShow/base/customPlots.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/output.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/deeplyNested/output.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/survival/output.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
  extension/src/test/fixtures/expShow/uncommittedDeps/output.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
  extension/src/test/util/experiments.ts
  extension/src/util/stdout.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/branchDivider/BranchDivider.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/AddAndRemoveBranches.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/styles.module.scss
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/messages.ts
  webview/src/stories/Table.stories.tsx
  webview/src/stories/util.ts
  webview/src/test/queries.ts
  webview/src/test/sort.ts
  webview/src/util/flags.ts
Labels: product

#3903 Add colons (":") to setup DVC details
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/dvc/DvcEnvInfoRow.tsx
Labels: product

#3914 Do not attempt to get commit message for the workspace record
  extension/src/experiments/index.ts
Labels: bug

#3917 Cleanup old branches before showing the experiments table
  extension/src/experiments/data/index.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/util.ts
Labels: bug

#3910 Make use of show experiments command for setup page
  extension/src/setup/index.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
Labels: 🏠 housekeeping

#3908 Add default test data to setup app tests
  webview/src/setup/components/App.test.tsx
Labels: 🏠 housekeeping

#3901 Add Remotes section to setup webview
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/executor.ts
  extension/src/setup/collect.test.ts
  extension/src/setup/collect.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/dvc/Dvc.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/remote/Connect.tsx
  webview/src/setup/components/remote/DvcUninitialized.tsx
  webview/src/setup/components/remote/MultiProjectRemotes.tsx
  webview/src/setup/components/remote/ProjectRemotes.tsx
  webview/src/setup/components/remote/RemoteDetails.tsx
  webview/src/setup/components/remote/Remotes.tsx
  webview/src/setup/components/remote/styles.module.scss
  webview/src/setup/components/shared/CliIncompatible.tsx
  webview/src/setup/components/shared/FocusDvcSection.tsx
  webview/src/setup/components/shared/util.ts
  webview/src/setup/components/studio/CliIncompatible.tsx
  webview/src/setup/components/studio/Studio.tsx
  webview/src/setup/state/dvcSlice.ts
  webview/src/setup/state/remoteSlice.ts
  webview/src/setup/store.ts
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/stories/Setup.stories.tsx
Labels: product

#3912 Fix typo in setup reducers
  webview/src/setup/components/App.tsx
  webview/src/setup/state/dvcSlice.ts
Labels: 🏠 housekeeping

#3911 Create default exp show output constant
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/reader.ts
  extension/src/test/cli/expShow.test.ts
Labels: 🏠 housekeeping

#3925 Ensure unique list of experiment passed to the rest of the app
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: bug

#3895 Add setup warning about latest tested version
  extension/src/cli/dvc/version.test.ts
  extension/src/cli/dvc/version.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/suite/setup/index.test.ts
  webview/icons/codicons.mjs
  webview/src/plots/components/App.test.tsx
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/SetupContainer.tsx
  webview/src/setup/state/dvcSlice.ts
  webview/src/shared/components/icons/Warning.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/shared/components/sectionContainer/InfoTooltip.tsx
  webview/src/shared/components/sectionContainer/SectionContainer.tsx
  webview/src/shared/components/sectionContainer/SectionDescription.tsx
  webview/src/shared/components/sectionContainer/styles.module.scss
  webview/src/shared/variables.scss
  webview/src/stories/Setup.stories.tsx
Labels: product

#3904 Add upgrade dvc button to setup when incompatible
  extension/src/setup/autoInstall.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/autoInstall.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/webview/contract.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/dvc/CliIncompatible.tsx
  webview/src/setup/components/messages.ts
Labels: product

#3927 Fix test console errors (add tbody)
  webview/src/setup/components/remote/MultiProjectRemotes.tsx
  webview/src/setup/components/remote/ProjectRemotes.tsx
Labels: 🏠 housekeeping

#3923 Increase timeout of flaky test
  extension/src/test/suite/config.test.ts
Labels: 🏠 housekeeping

#3937 Fix extension initialization on Windows (esm imports broken)
  extension/package.json
  extension/scripts/coverIntegrationTests.js
  extension/scripts/virtualenv-install.js
  extension/src/extension.ts
  extension/src/process/execution.test.ts
  extension/src/process/execution.ts
  extension/src/python/index.test.ts
  extension/src/python/index.ts
  extension/src/test/suite/cli/child.ts
  extension/src/test/suite/process/execution.test.ts
  extension/src/util/esm.ts
  package.json
  renovate.json
  scripts/virtualenv-install.ts
  yarn.lock
Labels: bug

#3930 Rename remote folder to remotes
  webview/src/setup/components/App.tsx
  webview/src/setup/components/remotes/Connect.tsx
  webview/src/setup/components/remotes/DvcUninitialized.tsx
  webview/src/setup/components/remotes/MultiProjectRemotes.tsx
  webview/src/setup/components/remotes/ProjectRemotes.tsx
  webview/src/setup/components/remotes/RemoteDetails.tsx
  webview/src/setup/components/remotes/Remotes.tsx
  webview/src/setup/components/remotes/styles.module.scss
Labels: 🏠 housekeeping

#3921 Fix row selection (duplicate experiments)
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/util/rows.ts
Labels: bug

#3936 Remove code slider fixed height
  webview/src/shared/components/codeSlider/styles.module.scss
Labels: 🏠 housekeeping

#3948 Add DVCLive reference to Experiments "Setup Complete"
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/experiments/NoData.tsx
Labels: product

#3955 Standardize title entries to title case
  extension/src/vscode/title.ts
Labels: 🏠 housekeeping

#3956 Add basic remote management
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/commands/external.ts
  extension/src/setup/collect.ts
  extension/src/setup/commands/index.ts
  extension/src/setup/commands/register.ts
  extension/src/setup/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/vscode/quickPick.test.ts
  extension/src/vscode/quickPick.ts
  extension/src/vscode/response.ts
  extension/src/vscode/title.ts
  extension/src/webview/contract.ts
  extension/src/workspace/util.ts
  webview/src/setup/components/messages.ts
  webview/src/setup/components/remotes/RemoteDetails.tsx
Labels: product

#3961 Fix DVC setup showing false info on incompatible global DVC
  extension/src/cli/dvc/discovery.ts
  extension/src/setup/runner.test.ts
Labels: bug

#3941 Use expShow once with multiple revisions
  extension/src/experiments/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
Labels: 🏠 housekeeping

#3968 Fix overflowing message
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#3970 Revert one expShow call
  extension/src/experiments/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
Labels: product

#3969 Show all branches when selecting
  extension/src/cli/git/constants.ts
  extension/src/cli/git/reader.test.ts
  extension/src/cli/git/reader.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
Labels: product

#3972 Use icons to show more or less commits and select branches
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  webview/icons/codicons.mjs
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/body/branchDivider/BranchDivider.tsx
  webview/src/experiments/components/table/body/commits/CommitsButton.tsx
  webview/src/experiments/components/table/body/commits/CommitsNavigation.tsx
  webview/src/experiments/components/table/body/commits/styles.module.scss
  webview/src/experiments/components/table/body/commitsAndBranches/AddAndRemoveBranches.tsx
  webview/src/experiments/components/table/body/commitsAndBranches/CommitsAndBranchesNavigation.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/shared/components/icons/Remove.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#3953 Fix setup redirection logic
  extension/src/commands/util.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/setup/index.test.ts
Labels: bug

#3986 Fix issues with messages from the plots webview
  extension/package.json
  extension/src/commands/external.ts
  extension/src/plots/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
Labels: bug

#3976 Bump min version of DVC to 2.57.0 (Live share to studio config option)
  README.md
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/contract.ts
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/cli/dvc/options.ts
  extension/src/cli/dvc/runner.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/setup/webview/messages.ts
  extension/src/test/cli/util.ts
  extension/src/test/suite/cli/dvc/runner.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
  extension/src/vscode/config.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/studio/Settings.tsx
  webview/src/setup/components/studio/styles.module.scss
Labels: product

#3987 Add DvcConfig class
  extension/src/cli/dvc/config.test.ts
  extension/src/cli/dvc/config.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/internal.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/setup/index.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#3965 Bump min version of DVC to 2.58.1 (Enable live plots for experiments running outside of the workspace)
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: product

#3996 Add storage types details to remote setup page
  webview/__mocks__/@vscode/webview-ui-toolkit/react.tsx
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/remotes/AmazonS3.tsx
  webview/src/setup/components/remotes/AzureBlobStorage.tsx
  webview/src/setup/components/remotes/CloudVersioning.tsx
  webview/src/setup/components/remotes/CloudVersioningLink.tsx
  webview/src/setup/components/remotes/Connect.tsx
  webview/src/setup/components/remotes/CustomAuth.tsx
  webview/src/setup/components/remotes/DvcUninitialized.tsx
  webview/src/setup/components/remotes/GoogleCloudStorage.tsx
  webview/src/setup/components/remotes/InfoText.tsx
  webview/src/setup/components/remotes/OtherStorageTypes.tsx
  webview/src/setup/components/remotes/RemoteDetails.tsx
  webview/src/setup/components/remotes/Remotes.tsx
  webview/src/setup/components/remotes/StorageSlider.tsx
  webview/src/setup/components/remotes/styles.module.scss
Labels: product

#4005 Move CodeSlider into Setup folder
  webview/src/setup/components/experiments/CodeSlider.tsx
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/experiments/NoData.tsx
  webview/src/setup/components/experiments/styles.module.scss
  webview/src/setup/components/remotes/CloudVersioning.tsx
  webview/src/setup/components/shared/CodeBlock.tsx
  webview/src/setup/components/shared/styles.module.scss
Labels: 🏠 housekeeping

#4006 Create shared panels component
  webview/src/setup/components/experiments/CodeSlider.tsx
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/experiments/styles.module.scss
  webview/src/setup/components/remotes/Connect.tsx
  webview/src/setup/components/remotes/DvcUninitialized.tsx
  webview/src/setup/components/remotes/RemoteDetails.tsx
  webview/src/setup/components/remotes/Remotes.tsx
  webview/src/setup/components/remotes/StorageSlider.tsx
  webview/src/setup/components/remotes/SupportedStorage.tsx
  webview/src/setup/components/remotes/styles.module.scss
  webview/src/setup/components/shared/CodeBlock.tsx
  webview/src/setup/components/shared/Panels.tsx
Labels: 🏠 housekeeping

#4007 Fix styles of supported storage panels
  webview/src/setup/components/remotes/AmazonS3.tsx
  webview/src/setup/components/remotes/CloudVersioning.tsx
  webview/src/setup/components/remotes/GoogleCloudStorage.tsx
  webview/src/setup/components/remotes/styles.module.scss
Labels: 🏠 housekeeping

#4004 Add link to show applicable extension for each storage provider
  extension/src/webview/factory.ts
  webview/icons/codicons.mjs
  webview/src/setup/components/remotes/AmazonS3.tsx
  webview/src/setup/components/remotes/AzureBlobStorage.tsx
  webview/src/setup/components/remotes/GoogleCloudStorage.tsx
  webview/src/setup/components/remotes/OtherStorageTypes.tsx
  webview/src/setup/components/remotes/ShowExtension.tsx
  webview/src/shared/components/icons/Extensions.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#3994 Show setup on new install
  README.md
  extension/package.json
  extension/src/extension.ts
  extension/src/setup/util.test.ts
  extension/src/setup/util.ts
  extension/src/vscode/config.ts
  extension/src/vscode/walkthrough.ts
Labels: product

#3993 Consolidate Setup and "Get Started" walkthrough
  README.md
  extension/package.json
  extension/resources/walkthrough/command-palette.md
  extension/resources/walkthrough/experiments-table.md
  extension/resources/walkthrough/images/install-dvc-status-bar-detected.png
  extension/resources/walkthrough/install-dvc.md
  extension/resources/walkthrough/setup-project.md
  extension/src/extension.ts
  extension/src/setup/util.test.ts
  extension/src/setup/util.ts
  extension/src/vscode/config.ts
  extension/src/vscode/walkthrough.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/GetStarted.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/components/dvc/DvcUnitialized.tsx
  webview/src/setup/components/experiments/Experiments.tsx
  webview/src/setup/components/shared/DvcNotSetup.tsx
Labels: product

#4016 Increase width of supported storage to remove scrollbar
  webview/src/setup/components/remotes/styles.module.scss
Labels: bug

#4015 Add capabilities to text mentioning storage provider extensions
  webview/src/setup/components/remotes/AmazonS3.tsx
  webview/src/setup/components/remotes/AzureBlobStorage.tsx
  webview/src/setup/components/remotes/GoogleCloudStorage.tsx
  webview/src/setup/components/remotes/ShowExtension.tsx
Labels: product

#4020 Improve "Get Started" walkthrough and welcome section
  extension/package.json
  extension/resources/walkthrough/command-palette.md
Labels: 🏠 housekeeping
