Repository iterative/vscode-dvc, pull requests merged in 2023-08, with the labels that each got.

#4394 Use instance spies to test plots webview messages
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
Labels: 🏠 housekeeping

#4391 Improve collection of summary columns efficiency
  extension/src/experiments/columns/model.ts
  extension/src/experiments/columns/util.ts
  extension/src/experiments/model/tree.ts
  extension/src/plots/model/index.ts
Labels: 🏠 housekeeping

#4396 Ensure experiment summary info (columns) is always available in the experiment table data
  extension/src/experiments/columns/collect/order.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/columns/model.ts
  extension/src/path/selection/model.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: bug

#4400 Update config tests
  extension/src/test/suite/config.test.ts
Labels: 🏠 housekeeping

#4402 Add toggle to show only changed columns in experiments table
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/persistence/constants.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/icons/codicons.mjs
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/emptyState/AddColumns.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/messages.ts
  webview/src/shared/components/icons/Table.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/stories/Table.stories.tsx
Labels: product

#4412 Fix plots not showing on first experiment run
  extension/src/plots/paths/collect.ts
Labels: bug

#4406 Update filter icon in experiment table column header cells
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
Labels: 🏠 housekeeping

#4407 Refactor experiment table header context menu
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/MergeHeaderGroups.tsx
  webview/src/experiments/components/table/header/TableHeader.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/components/table/header/TableHeaderCellContents.tsx
  webview/src/experiments/components/table/header/util.ts
Labels: 🏠 housekeeping

#4405 Collect webview messages async
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#4372 Add "Image by Step" plots
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/fileSystem/util.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.test.ts
  extension/src/test/fixtures/plotsDiff/comparison/multi.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/stories/ComparisonTable.stories.tsx
Labels: product

#4319 Add "image by step" plots to comparison section
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/index.test.ts
  extension/src/fileSystem/util.ts
  extension/src/plots/model/collect.test.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/fixtures/plotsDiff/staticImages/image/0.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/1.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/10.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/11.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/12.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/13.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/14.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/2.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/3.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/4.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/5.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/6.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/7.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/8.jpg
  extension/src/test/fixtures/plotsDiff/staticImages/image/9.jpg
  extension/src/test/suite/plots/index.test.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableCell.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableLoadingCell.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMissingCell.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx
  webview/src/plots/components/comparisonTable/comparisonTableSlice.ts
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/stories/ComparisonTable.stories.tsx
Labels: 🏠 housekeeping

#4415 Add filter options to experiment table header context menu
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/quickPick.test.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/test/experimentsTable.tsx
Labels: product

#4416 Reorder experiment table indicator icons
  webview/src/experiments/components/table/Indicators.tsx
Labels: 🏠 housekeeping

#4417 Move integration test webview message spies towards instance spies
  extension/src/test/suite/experiments/columns/tree.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
  extension/src/webview/repository.ts
Labels: 🏠 housekeeping

#4440 Add GIT_OPTIONAL_LOCKS=0 to all Git calls
  extension/src/cli/git/options.ts
  extension/src/cli/git/reader.test.ts
Labels: 🏠 housekeeping

#4441 Reduce calls to Git (Setup webview)
  extension/src/setup/index.ts
Labels: 🏠 housekeeping

#4425 Followup on fixing broken plots on first exp run
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
Labels: 🏠 housekeeping

#4427 Reduce wait time in test utils
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#4434 Only open experiments webview in integration tests when necessary
  extension/src/test/suite/experiments/columns/tree.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: 🏠 housekeeping

#4432 Fix sorts and filters for dep columns
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/like.ts
  extension/src/experiments/columns/util.test.ts
  extension/src/experiments/columns/util.ts
  extension/src/experiments/model/filterBy/index.test.ts
  extension/src/experiments/model/filterBy/index.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/model/sortBy/index.test.ts
  extension/src/experiments/model/sortBy/index.ts
  extension/src/experiments/model/sortBy/quickPick.ts
  extension/src/vscode/title.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
Labels: bug

#4446 Exclude untracked dvc.yaml and dvc.lock files from the DVC SCM tree
  extension/src/repository/model/index.ts
Labels: bug

#4435 Fix Created column presence in show only changed
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
Labels: bug

#4444 Replace git diff call with git extension state
  extension/src/cli/git/reader.ts
  extension/src/extensions/git.ts
  extension/src/repository/data/index.ts
  extension/src/repository/index.ts
  extension/src/repository/model/index.test.ts
  extension/src/repository/model/index.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/repository/index.test.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/repository/util.ts
Labels: 🏠 housekeeping

#4398 Add action menu button to zoomable plots
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/webviewSlice.ts
  webview/src/stories/Plots.stories.tsx
Labels: product

#4453 Move stylelint into webview package
  package.json
  webview/package.json
Labels: 🏠 housekeeping

#4461 Fix plot actions button showing on sticky ribbon
  webview/src/plots/components/styles.module.scss
Labels: bug

#4458 Fix Comparison Plot "Image By Step" height
  extension/src/test/fixtures/plotsDiff/staticImages/image/7.jpg
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
  webview/src/stories/Plots.stories.tsx
Labels: bug

#4467 Use is Python extension installed for setup
  extension/src/setup/index.ts
  extension/src/setup/webview/contract.ts
  extension/src/test/suite/setup/index.test.ts
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/components/dvc/CliUnavailable.tsx
  webview/src/setup/state/dvcSlice.ts
  webview/src/stories/Setup.stories.tsx
Labels: bug

#4463 Do not wait to collect files to send exp data
  extension/src/experiments/data/index.ts
Labels: 🏠 housekeeping

#4478 Fix image by step plots breaking on nonexistent steps
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx
Labels: bug

#4481 Fix comparison table test
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRows.tsx
Labels: 🏠 housekeeping

#4479 Refactor setting of experiment table column order via drag and drop
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
  webview/src/experiments/util/columns.ts
Labels: 🏠 housekeeping

#4495 Update experiments table column data
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/columns/Columns.tsx
  webview/src/experiments/components/table/content/ExperimentHeader.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
  webview/src/experiments/components/table/header/TableHeaderCell.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/buildColumns.tsx
  webview/src/experiments/util/columns.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/sort.ts
  webview/src/test/tableDataFixture.ts
Labels: 🏠 housekeeping

#4484 Remove unused redux slice from experiments table
  webview/src/experiments/state/headersSlice.ts
  webview/src/experiments/store.ts
Labels: 🏠 housekeeping

#4483 Have experiment webview redirect to setup when there is no data
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/components/emptyState/AddColumns.tsx
  webview/src/experiments/components/emptyState/GetStarted.tsx
  webview/src/experiments/components/emptyState/Welcome.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: bug

#4501 Fix experiment table created column
  webview/src/experiments/components/table/body/columns/Columns.tsx
  webview/src/stories/Table.stories.tsx
Labels: bug

#4500 Add refresh button to experiments tree cli errors
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/tree/index.ts
Labels: product

#4502 Fix scheduled CLI output test (extra image plots)
  extension/src/test/cli/dataStatus.test.ts
  extension/src/test/cli/plotsDiff.test.ts
Labels: bug

#4508 Fix tests
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/plots/paths/tree.test.ts
Labels: 🏠 housekeeping

#4503 Avoid more unnecessary experiments table re-renders
  webview/src/experiments/components/table/Table.tsx
  webview/src/experiments/components/table/body/ExperimentGroup.tsx
  webview/src/experiments/components/table/body/NestedRow.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/body/TableBody.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/WorkspaceRowGroup.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
Labels: 🏠 housekeeping

#4506 Reduce Comparison "Image By Step" calls to backend
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx
Labels: 🏠 housekeeping

#4512 Fix show only changed behaviour
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/header/TableHead.tsx
Labels: bug

#4510 Add Scikit-learn and YOLO to other frameworks supported by DVCLive
  webview/src/setup/components/experiments/OtherFrameworks.tsx
Labels: product

#4511 Make redux utils generic
  webview/src/experiments/state/rowSelectionSlice.ts
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/util/array.ts
  webview/src/util/objects.ts
Labels: 🏠 housekeeping

#4515 Update setup studio status icon
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/App.tsx
Labels: 🏠 housekeeping

#4516 Fix "Image By Step" step number inaccuracy
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/comparisonTable/cell/ComparisonTableMultiCell.tsx
  webview/src/stories/ComparisonTable.stories.tsx
Labels: bug

#4529 Hide refresh experiments from the command palette
  extension/package.json
Labels: bug

#4522 Fix possibly cuttoff cli errors in tree views
  extension/src/experiments/model/tree.test.ts
  extension/src/experiments/model/tree.ts
  extension/src/plots/paths/tree.test.ts
  extension/src/repository/model/tree.test.ts
  extension/src/repository/model/tree.ts
  extension/src/tree/index.ts
Labels: bug

#4543 Remove click listener from experiment name and sha
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
Labels: bug

#4544 Add copy sha and name to experiment table row context menu
  extension/src/__mocks__/vscode.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/vscode/clipboard.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
Labels: product

#4527 Restructure plots path tree for nested dvc.yaml paths
  extension/src/cli/dvc/constants.ts
  extension/src/experiments/columns/tree.ts
  extension/src/path/selection/tree.ts
  extension/src/plots/multiSource/collect.ts
  extension/src/plots/paths/collect.test.ts
  extension/src/plots/paths/collect.ts
  extension/src/plots/paths/model.test.ts
  extension/src/plots/paths/tree.ts
  extension/src/test/suite/plots/index.test.ts
Labels: bug

#4564 Update collection of files which trigger exp show updates
  extension/src/experiments/data/collect.test.ts
  extension/src/experiments/data/collect.ts
Labels: bug

#4565 Accomodate new DVCLive signal file format
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: 🏠 housekeeping

#4557 Add copy shareable Studio link to experiments table
  extension/package.json
  extension/src/cli/git/reader.ts
  extension/src/experiments/index.ts
  extension/src/experiments/studio.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/setup/index.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/vscode/clipboard.ts
  extension/src/webview/contract.ts
  webview/icons/codicons.mjs
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/messages.ts
  webview/src/shared/components/icons/Link.tsx
  webview/src/shared/components/icons/index.ts
  webview/src/stories/Table.stories.tsx
  yarn.lock
Labels: product

#4566 Plot finished DVCLive only experiments
  extension/src/experiments/index.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/plots/index.ts
Labels: product

#4571 Create watcher specifically for temp queue directories
  extension/src/cli/dvc/constants.ts
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
Labels: bug

#4577 Add "Matrix Pipeline Stage" dvc snippet
  extension/snippets/dvc-yaml.code-snippets
Labels: product

#4580 Call Studio API will all refs available on the Git remote
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/studio.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
Labels: 🏠 housekeeping

#4579 Use DVCLive step completed signal file events to trigger experiments and plots data updates
  extension/src/cli/dvc/constants.ts
  extension/src/experiments/data/index.ts
  extension/src/plots/data/index.ts
Labels: bug
