Repository iterative/vscode-dvc, pull requests merged in 2023-07, with the labels that each got.

#4202 Update plot smooth control background color
  webview/src/plots/components/styles.module.scss
Labels: product

#4181 Add "Export Raw Data" option to plot popup
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/setup-tests.js
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/hooks/useMutationObserver.ts
  webview/src/plots/util/messages.ts
Labels: product

#4212 Improve table indicators
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/util/strings.ts
Labels: product

#4214 Fix force SCM action regex
  extension/src/cli/dvc/output.ts
  extension/src/repository/commands/index.test.ts
Labels: bug

#4218 Use `onNewView` instead of `MutationObserver` in zoomed in plot
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/hooks/useMutationObserver.ts
Labels: 🏠 housekeeping

#4228 Add dvc.yaml into files used to show editor/title icons
  extension/package.json
  extension/src/experiments/context.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/vscode/recommend.test.ts
  extension/src/vscode/context.ts
Labels: product

#4224 Update DVCLive examples in Setup
  webview/src/setup/components/App.test.tsx
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/experiments/OtherFrameworks.tsx
  webview/src/setup/components/experiments/styles.module.scss
  webview/src/setup/snippets/huggingFace.py
  webview/src/setup/snippets/keras.py
  webview/src/setup/snippets/pyTorch.py
  webview/src/setup/snippets/pythonApi.py
Labels: product

#4225 Update copy around adding a new stage/defining a pipeline for a project without one
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
Labels: product

#4233 Add dvc.yaml pipeline snippets
  extension/package.json
  extension/snippets/dvc-yaml.code-snippets
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
Labels: product

#4234 Add dvc.yaml top level plot snippets
  extension/snippets/dvc-yaml.code-snippets
Labels: product

#4235 Add dvc.yaml artifact snippets
  extension/snippets/dvc-yaml.code-snippets
Labels: product

#4245 Correct extension reference in snippet
  extension/snippets/dvc-yaml.code-snippets
Labels: 🏠 housekeeping

#4244 Display DAG in Markdown Preview editor
  README.md
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/reader.test.ts
  extension/src/cli/dvc/reader.ts
  extension/src/commands/external.ts
  extension/src/data/index.ts
  extension/src/extension.ts
  extension/src/pipeline/data.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/register.ts
  extension/src/pipeline/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/pipeline/workspace.test.ts
  extension/src/vscode/config.ts
  extension/src/vscode/recommend.test.ts
  extension/src/vscode/recommend.ts
Labels: product

#4255 Apply product feedback to dvc.yaml snippets
  extension/snippets/dvc-yaml.code-snippets
Labels: product

#4258 Add DVCLive snippets
  extension/package.json
  extension/snippets/dvclive.code-snippets
  webview/src/setup/components/experiments/DvcLiveExamples.tsx
  webview/src/setup/components/remotes/AmazonS3.tsx
  webview/src/setup/components/remotes/ShowExtension.tsx
  webview/src/setup/components/remotes/styles.module.scss
  webview/src/setup/components/shared/InfoText.tsx
  webview/src/setup/components/shared/styles.module.scss
Labels: product

#4252 Add CSV export option to zoomed in plots
  extension/package.json
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/plots/model/collect.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/util/messages.ts
  yarn.lock
Labels: product

#4220 Save smooth plot values across sessions
  extension/src/persistence/constants.ts
  extension/src/plots/model/index.ts
  extension/src/plots/webview/contract.ts
  extension/src/plots/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/plotsDiff/index.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/webview/contract.ts
  webview/src/plots/components/App.test.tsx
  webview/src/plots/components/Plots.tsx
  webview/src/plots/components/ZoomablePlot.tsx
  webview/src/plots/components/ZoomedInPlot.tsx
  webview/src/plots/components/styles.module.scss
  webview/src/plots/components/templatePlots/TemplatePlotsGrid.tsx
  webview/src/plots/components/templatePlots/TemplateVegaLite.tsx
  webview/src/plots/components/templatePlots/templatePlotsSlice.ts
  webview/src/plots/components/webviewSlice.ts
  webview/src/plots/hooks/useGetPlot.ts
  webview/src/plots/util/messages.ts
Labels: product

#4264 Handle non-standard experiment pipeline configurations
  extension/src/cli/dvc/reader.ts
  extension/src/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/data.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/model/collect.test.ts
  extension/src/pipeline/model/collect.ts
  extension/src/pipeline/model/index.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/extension.test.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/test/suite/pipeline/util.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/setup/util.ts
  extension/src/test/suite/util.ts
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
Labels: product

#4272 Refactor stubWorkspaceExperimentsGetters
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
Labels: 🏠 housekeeping

#4273 Focus pipeline when dvc.yaml file is open in the active editor
  extension/package.json
  extension/src/pipeline/context.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/workspace.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/pipeline/index.test.ts
  extension/src/test/suite/util.ts
  extension/src/vscode/context.ts
Labels: product

#4282 Remove moduleResolution from tsconfig
  extension/tsconfig.json
Labels: 🏠 housekeeping

#4283 Exclude sub-project files from file and editor watchers
  extension/src/data/index.ts
  extension/src/experiments/context.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/extension.ts
  extension/src/fileSystem/index.test.ts
  extension/src/fileSystem/index.ts
  extension/src/pipeline/context.ts
  extension/src/pipeline/data.ts
  extension/src/pipeline/index.ts
  extension/src/pipeline/workspace.ts
  extension/src/plots/data/index.ts
  extension/src/plots/index.ts
  extension/src/plots/workspace.ts
  extension/src/repository/data/index.test.ts
  extension/src/repository/data/index.ts
  extension/src/repository/index.ts
  extension/src/repository/workspace.ts
  extension/src/setup/collect.test.ts
  extension/src/setup/collect.ts
  extension/src/setup/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/pipeline/data.test.ts
  extension/src/test/suite/pipeline/util.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/test/suite/repository/util.ts
  extension/src/workspace/index.ts
Labels: bug

#4292 Update copy in add stage component
  webview/src/experiments/components/AddStage.tsx
  webview/src/experiments/components/App.test.tsx
Labels: product

#4262 Remove `dvc_data_version_info` from plot values
  extension/src/plots/model/collect.ts
  extension/src/test/fixtures/plotsDiff/template/smoothTemplatePlot.ts
Labels: 🏠 housekeeping

#4293 Add columns indicator (select columns) to table indicators
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/Indicators.tsx
Labels: product

#4294 Add select first experiment table columns quick pick
  extension/package.json
  extension/src/commands/external.ts
  extension/src/experiments/columns/model.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/workspace.ts
  extension/src/path/selection/quickPick.test.ts
  extension/src/path/selection/quickPick.ts
  extension/src/plots/index.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/columns/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/vscode/title.ts
  webview/src/experiments/components/Experiments.tsx
Labels: product

#4295 Add select column options to table header cell context menu
  extension/src/experiments/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
Labels: product

#4305 Set default number of displayed commits to 1 for non-current branches in the experiments table
  extension/src/cli/dvc/constants.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/util.ts
Labels: product

#4303 Add move to start option to experiment table header cell context menu
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
Labels: product

#4304 Clean up hide column terminology
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/header/ContextMenuContent.tsx
Labels: 🏠 housekeeping

#4308 Add not missing filter for experiments table
  extension/src/experiments/model/filterBy/index.test.ts
  extension/src/experiments/model/filterBy/index.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: product

#4306 Add matchOnDetail and matchOnDescription to all quick picks
  extension/src/experiments/model/quickPick.test.ts
  extension/src/experiments/model/quickPick.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/vscode/quickPick.test.ts
  extension/src/vscode/quickPick.test.ts
  extension/src/vscode/quickPick.ts
Labels: bug

#4307 Standardise column like quick pick
  extension/src/experiments/columns/quickPick.test.ts
  extension/src/experiments/columns/quickPick.ts
  extension/src/plots/model/quickPick.test.ts
Labels: 🏠 housekeeping

#4312 Update Studio settings section
  webview/src/setup/components/studio/Settings.tsx
  webview/src/setup/components/studio/styles.module.scss
Labels: product

#4314 Add shown/hidden indicator to select first column quick pick
  extension/src/experiments/index.ts
  extension/src/path/selection/quickPick.ts
  extension/src/test/suite/experiments/columns/tree.test.ts
Labels: product

#4315 Rename select columns commands and events
  extension/package.json
  extension/src/commands/external.ts
  extension/src/test/suite/experiments/columns/tree.test.ts
Labels: 🏠 housekeeping

#4324 Show Experiment Remote Status
  extension/src/cli/git/reader.ts
  extension/src/data/index.ts
  extension/src/experiments/commands/index.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/workspace.ts
  extension/src/test/fixtures/expShow/base/remoteExpRefs.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  webview/icons/codicons.mjs
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/body/Row.tsx
  webview/src/experiments/components/table/styles.module.scss
  webview/src/experiments/util/messages.ts
  webview/src/shared/components/icons/Cloud.tsx
  webview/src/shared/components/icons/CloudUpload.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#4342 Run remote experiments data update in the background
  extension/src/data/index.ts
  extension/src/experiments/data/index.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.test.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/pipeline/data.ts
  extension/src/plots/data/index.ts
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/test/suite/plots/index.test.ts
  extension/src/test/suite/plots/util.ts
  extension/src/test/suite/util.ts
Labels: 🏠 housekeeping

#4340 Fix cloud icon alignment in experiments table
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#4339 Use trim and split util
  extension/src/experiments/model/collect.ts
Labels: 🏠 housekeeping

#4343 Disable exp push when experiment is running in the workspace
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/styles.module.scss
Labels: bug

#4356 Avoid reprocessing duplicate git log commits
  extension/src/experiments/model/collect.ts
Labels: 🏠 housekeeping

#4355 Add reset number of commits to show for a branch button to experiments table
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/messages.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/webview/contract.ts
  webview/icons/codicons.mjs
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/table/body/commits/CommitsButton.tsx
  webview/src/experiments/components/table/body/commits/CommitsNavigation.tsx
  webview/src/experiments/util/messages.ts
  webview/src/shared/components/icons/Discard.tsx
  webview/src/shared/components/icons/index.ts
Labels: product

#4346 Remove column merge logic
  extension/src/experiments/columns/collect/deps.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/columns/constants.ts
  extension/src/experiments/columns/like.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/experiments/model/filterBy/quickPick.test.ts
  extension/src/experiments/model/filterBy/quickPick.ts
  extension/src/experiments/model/sortBy/quickPick.test.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/base/columns.ts
  extension/src/test/fixtures/expShow/dataTypes/columns.ts
  extension/src/test/fixtures/expShow/deeplyNested/columns.ts
  extension/src/test/fixtures/expShow/deeplyNested/maxHeight.ts
  extension/src/test/fixtures/expShow/survival/columns.ts
  webview/src/experiments/components/App.test.tsx
Labels: 🏠 housekeeping

#4353 Improve performance of experiment column collection
  extension/src/experiments/columns/collect/deps.ts
  extension/src/experiments/columns/collect/index.test.ts
  extension/src/experiments/columns/collect/index.ts
  extension/src/experiments/columns/collect/metricsAndParams.ts
  extension/src/experiments/columns/collect/util.ts
  extension/src/experiments/columns/model.test.ts
  extension/src/test/fixtures/expShow/deeplyNested/maxHeight.ts
Labels: 🏠 housekeeping

#4354 Remove await from inside of loops
  extension/src/experiments/data/index.ts
  extension/src/repository/model/collect.ts
Labels: 🏠 housekeeping

#4363 Apply experiment table filters to commits
  extension/src/experiments/index.ts
  extension/src/experiments/model/filterBy/collect.ts
  extension/src/experiments/model/filterBy/tree.ts
  extension/src/experiments/model/index.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/Experiments.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: product

#4364 Refactor experiment table branch data
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/rows.ts
  extension/src/test/fixtures/expShow/deeplyNested/rows.ts
  extension/src/test/fixtures/expShow/survival/rows.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/Indicators.tsx
  webview/src/experiments/components/table/RowSelectionContext.tsx
  webview/src/experiments/components/table/Table.test.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/components/table/body/TableContent.test.tsx
  webview/src/experiments/components/table/body/TableContent.tsx
  webview/src/experiments/components/table/body/util.ts
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/experiments/util/rows.ts
  webview/src/stories/Table.stories.tsx
Labels: 🏠 housekeeping

#4359 Rename experiment status to executor status
  extension/src/cli/dvc/contract.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.test.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/model/status/collect.test.ts
  extension/src/experiments/model/status/collect.ts
  extension/src/experiments/model/status/index.test.ts
  extension/src/experiments/model/status/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/test/fixtures/expShow/base/output.ts
  extension/src/test/fixtures/expShow/base/rows.ts
  extension/src/test/suite/experiments/model/sortBy/tree.test.ts
  extension/src/test/util/experiments.ts
  webview/src/experiments/components/table/body/Cell.tsx
  webview/src/experiments/components/table/body/CellRowActions.tsx
  webview/src/experiments/components/table/body/ExperimentStatusIndicator.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#4368 Increase timeouts of webview tests
  extension/src/test/suite/plots/index.test.ts
Labels: 🏠 housekeeping

#4375 Use instance spies to test experiments webview messages
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/util.ts
Labels: 🏠 housekeeping

#4376 Fix show setup/experiments on extension initialization
  extension/src/commands/util.ts
  extension/src/setup/index.ts
  extension/src/test/suite/setup/util.ts
Labels: bug

#4385 Watch a small directory for testing purposes
  extension/src/test/suite/setup/util.ts
Labels: 🏠 housekeeping
