Repository iterative/vscode-dvc, pull requests merged in 2024-01, with the labels that each got.

#5175 Revert @vscode/extension-telemetry to 0.8.5
  extension/package.json
  renovate.json
  yarn.lock
Labels: bug

#5187 Update ribbon error banner to a div
  webview/src/plots/components/ribbon/Errors.tsx
  webview/src/plots/components/ribbon/Ribbon.tsx
  webview/src/plots/components/ribbon/styles.module.scss
Labels: 🏠 housekeeping

#5194 Replace switch statements that feed the webviews stores
  webview/src/experiments/components/App.tsx
  webview/src/plots/components/App.tsx
  webview/src/setup/components/App.tsx
  webview/src/setup/state/webviewSlice.ts
  webview/src/shared/dispatchActions.ts
  webview/src/shared/hooks/useVsCodeMessaging.ts
Labels: 🏠 housekeeping

#5195 Update filesystem watcher integration tests
  extension/src/test/suite/experiments/data/index.test.ts
  extension/src/test/suite/plots/data/index.test.ts
  extension/src/test/suite/repository/data/index.test.ts
  extension/src/test/suite/timeouts.ts
Labels: 🏠 housekeeping

#5203 Remove redundant version check from exp rename code
  extension/src/cli/dvc/version.ts
  extension/src/experiments/commands/register.ts
  extension/src/test/suite/experiments/index.test.ts
Labels: 🏠 housekeeping

#5204 Remove redundant checkpoints code
  extension/package.json
  extension/src/cli/dvc/constants.ts
  extension/src/cli/dvc/runner.ts
  extension/src/commands/external.ts
  extension/src/experiments/commands/register.ts
  extension/src/experiments/index.ts
  extension/src/experiments/model/collect.ts
  extension/src/experiments/model/index.ts
  extension/src/experiments/webview/contract.ts
  extension/src/experiments/webview/messages.ts
  extension/src/experiments/workspace.test.ts
  extension/src/experiments/workspace.ts
  extension/src/telemetry/constants.ts
  extension/src/test/fixtures/expShow/base/tableData.ts
  extension/src/test/fixtures/expShow/dataTypes/tableData.ts
  extension/src/test/fixtures/expShow/deeplyNested/tableData.ts
  extension/src/test/suite/experiments/index.test.ts
  extension/src/test/suite/experiments/model/filterBy/tree.test.ts
  extension/src/test/suite/experiments/model/tree.test.ts
  extension/src/test/suite/experiments/workspace.test.ts
  extension/src/vscode/context.ts
  extension/src/webview/contract.ts
  webview/src/experiments/components/App.test.tsx
  webview/src/experiments/components/App.tsx
  webview/src/experiments/components/table/body/RowContextMenu.tsx
  webview/src/experiments/state/tableDataSlice.ts
  webview/src/stories/Table.stories.tsx
  webview/src/test/experimentsTable.tsx
Labels: 🏠 housekeeping

#5211 Remove console statements in tests
  webview/src/plots/components/comparisonTable/ComparisonTableHeader.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.test.tsx
Labels: 🏠 housekeeping

#5210 Add on hover style to experiments table header cells
  webview/src/experiments/components/table/styles.module.scss
Labels: 🏠 housekeeping

#5221 Remove the rename command from the DVC tracked tree
  extension/package.json
  extension/src/cli/dvc/executor.test.ts
  extension/src/cli/dvc/executor.ts
  extension/src/commands/external.ts
  extension/src/repository/model/tree.ts
  extension/src/telemetry/constants.ts
  extension/src/test/suite/repository/model/tree.test.ts
  extension/src/vscode/title.ts
Labels: 🏠 housekeeping

#5240 Move bounding box class legend into its own collapsible row
  webview/src/plots/components/comparisonTable/ComparisonTable.test.tsx
  webview/src/plots/components/comparisonTable/ComparisonTablePinnedContentRow.tsx
  webview/src/plots/components/comparisonTable/ComparisonTableRow.tsx
  webview/src/plots/components/comparisonTable/styles.module.scss
Labels: product

#5251 Do not brick the extension when trying to get user_id for telemetry
  extension/src/telemetry/uuid.ts
Labels: bug
